### ISSUE TITLE
Edinburgh Techmeetup 10 August 2016

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/edinburgh#100]
## Ship List
- [ ] Email SkyScanner Reception to make sure they're ready for us
- [ ] Open Tech Calendar event ([link to event])
- [x] Drinks ordered
- [ ] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [ ] Pizza paid for
- [x] Speakers confirmed (#97, #99)
- [ ] Confirm volunteer to man the door
- [ ] Confirmed speakers video and internet requirements
- [x] Website updated ([link to commit])
- [x] Email announcement sent
- [ ] Confirm organisers present
    - [ ] @rwillmer
    - [x] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm
    - [ ] @marksutherland

**Comment by MariusCiocanel** [comment]
we should check with @klutz if he's still fine to do the talk https://github.com/techmeetup/edinburgh/issues/99 in August

**Comment by klutz** [comment]
Yup, I'm still good for #99 in August.

**Comment by MariusCiocanel** [comment]
🚢'd! Thanks everyone.
