### ISSUE TITLE
CP for the Sudoku intolerant

### ISSUE THREAD

**Issue by alastairandrew** [techmeetup/edinburgh#102]
Hi, 

I was wondering if I could volunteer a talk next month. I was planning on doing an Intro to Constraint Programming by breaking down some of the puzzles from Alex Bellos' column in the Guardian then moving on to some more real-world applications. 

Thanks,
Alastair

**Comment by marksutherland** [comment]
Hi @alastairandrew !
Are you still interested in talking in September? We probably have space and it sounds quite interesting :)

**Comment by alastairandrew** [comment]
Hi @marksutherland, 

Yeah sure. I need to actually write some slides, but I'm game.

**Comment by marksutherland** [comment]
Excellent, thank you very much!

I'm not entirely sure how familiar you are with TMU so I'll give you the full speil:

Folk usually start arriving from 6.30pm and there's free beer and pizza and time to chat and gossip. We do a round of introductions at about 7.30pm, then after a break we do the first talk (~25 mins) with time for a few questions. Then there's another break then the second talk. We usually finish by 9pm then head to the pub.

The AV setup at skyscanner is pretty good, so if you want to use your own laptop there is mini display port and HDMI available, but there is also a PC to present from. Either way, you should probably send me a copy of your slides by Tuesday night as a backup, and bring a copy on the night yourself. There will hopefully be a livestream on Youtube that stays up for posterity, let me know if you'd rather not be recorded.

I think that's most of the main details, but if you have any questions or concerns let me know and I'll see what I can do. Thanks again!

**Comment by alastairandrew** [comment]
Thanks for the info. I've been along to a few Tech Meetups so I know the
rough drill.

I'd probably aim to present from my Mac, I want to do a few bits of live
coding. It's reasonably modern so (fingers crossed) there shouldn't be any
issues around display ports.

**Comment by alastairandrew** [comment]
I'm at the mercy of the tram currently, should be there before 7 though

**Comment by alastairandrew** [comment]
I meant to ask do you want my slides from Wednesday? I can embed the links
to some resources in there too. I don't know if you normally host them
somewhere.

AA

**Comment by MariusCiocanel** [comment]
Speakers usually send an email to the mailing list with a https://speakerdeck.com/  link to their slides. The mailing list is http://groups.google.com/group/techmeetup?pli=1 if you've not signed up to it already. Feel free to join the mailing list and email the slides.
Tip: the subject of your email & a link to it will be automatically tweeted from the Techmeetup twitter account
