### ISSUE TITLE
Edinburgh Techmeetup 14 September 2016

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/edinburgh#103]
## Ship List
- [ ] Email SkyScanner Reception to make sure they're ready for us
- [ ] Open Tech Calendar event ([link to event])
- [x] Drinks ordered
- [x] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [x] Pizza paid for
- [ ] Speakers confirmed (<#123, #456 [links to issues]>)
- [ ] Confirm volunteer to man the door
- [ ] Confirmed speakers video and internet requirements
- [x] Website updated ([link to commit])
- [ ] Email announcement sent
- [ ] Confirm organisers present
    - [ ] @rwillmer
    - [x] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm
    - [ ] @marksutherland

**Comment by MariusCiocanel** [comment]
A bit late with this issue but ¯\_(ツ)_/¯

**Comment by marksutherland** [comment]
🚢 ed!
