### ISSUE TITLE
Steve Kilbane - Old-school Security: Lock-picking Basics

### ISSUE THREAD

**Issue by kilbswhitecrow** [techmeetup/edinburgh#106]
An introduction to how pin-tumbler locks work, and how to pick them.

Previous TMU talks were on how processors boot up, and addressing in the SHARC DSP.

**Comment by marksutherland** [comment]
@kilbswhitecrow is going to talk about this in December

**Comment by marksutherland** [comment]
Hi @kilbswhitecrow , just wanted to confirm you're still on for Wednesday?
I know you're familiar with how things usually go. If you want to present from your laptop, there are hdmi and mini display port adapaters available, alternatively there's a PC we can present from. It's probably a good idea to email me a copy of your slides by Tuesday night as a back up just in case.
Is the title in the topic the one you want to go with? Pawel has a fancy new streaming set up which can switch between the slides and the camera and does proper lower thirds etc.
Let me know if you have any questions and concerns and I'll see what I can do.

**Comment by kilbswhitecrow** [comment]
Yep, good to go. Title's still good, too. I'll be bringing my MacBook. Slides are Keynote, though I forget which rev. I think my own adaptor is to VGA, so it's good that you've already got one.

Do you want the presentation as an attachment here, or emailed?

**Comment by marksutherland** [comment]
If you can attach it here that might be best as I can't actually make it along this month as it clashes with my work night out. I'll make sure someone who's going along knows where to look.
There are definitely display port -> hdmi adapters for plugging into macbooks so you should be fine.
I should have the email out later tonight. Let me know if you need anything else and good luck!

**Comment by kilbswhitecrow** [comment]
[LockPickingDraft.key.zip](https://github.com/techmeetup/edinburgh/files/650499/LockPickingDraft.key.zip)
