### ISSUE TITLE
Steve Kilbane - Misc C Compiler stuff

### ISSUE THREAD

**Issue by kilbswhitecrow** [techmeetup/edinburgh#107]
As a compiler developer, Steve can do several different talks about how C compilers work, e.g. the vagueness of the C language std, optimisation, how to deal with silicon bugs,  etc.

**Comment by marksutherland** [comment]
Hi @kilbswhitecrow !

Would you be able to speak next week on the 12th? If not, how about November or December?

Also, do you have anything specific in mind? Thanks for volunteering!

**Comment by kilbswhitecrow** [comment]
Damnit, I assumed that replying to the email was sufficient. I wondered why there hadn't been any reply for almost a week... I wrote:

I can do the lock-picking talk [on the 12th]. The compiler-related talks still need writing, but November is plausible. I can't guarantee availability for December, though.

For the compiler-related ones, the three areas that came to mind were:
- user-facing problems, such as data-type variances.
- general optimisation theory, not dissimilar from what a modern text book would say.
- general gnarliness, such as silicon bugs, customer support, relations, position-independent code.

**Comment by marksutherland** [comment]
I think my advice would be to pick something that you and few others would be able to talk about, as you'll likely be more engaged with the subject matter and the audience are most likely to learn something they didn't know. If all else fails, go for whatever you find most engaging yourself :)

I'm a bit wary of the lock-picking talk tbh as I suspect it might be a little too off the normal beaten path for TMU, but that said I know it's quite popular around tech circles, and I've generally found similar talks quite engaging. One of my favorite memories of EMF this year was the entire camp patiently waiting for a guy who was filing away at a key for a lock just before the closing ceremony and the massive cheer when he finally got it unlocked :)

If you want, I could ask the audience tomorrow what they'd prefer?

Anyway, thanks for getting in touch again, sorry about the communication hitch!

**Comment by kilbswhitecrow** [comment]
Rightio. We can chat about it tonight.

**Comment by marksutherland** [comment]
Thanks for talking in December, shame I missed it. Would you be up for doing the C compiler stuff later in the year? If so, I'll leave this open :)

**Comment by kilbswhitecrow** [comment]
Sure!

**Comment by MariusCiocanel** [comment]
Hi @kilbswhitecrow. Would you like to do this C compiler talk on the 11th of July?

**Comment by kilbswhitecrow** [comment]
Hi Marius,

Sorry about the delay in replying - I've been out of the country for a bit.

Yes, I think I can do that. I'll give you a more reasonable title when I have a better idea of what it looks like.

steve

**Comment by MariusCiocanel** [comment]
Hi @kilbswhitecrow ,

I'm about to send the announcement email and wanted to confirm you're still good to go for Wednesday. I also wanted to let you know that this month's event is happening in CodeBase, 38 Castle Terrace EH3 9DZ.

Please let me know

**Comment by kilbswhitecrow** [comment]
Yep, will be good to go. Current working title is "Anatomy of a C Compiler".

Codebase: check.

**Comment by MariusCiocanel** [comment]
🚢d! Thanks for the talk!
