### ISSUE TITLE
Martin Hawksey, The Google Analytics of Things

### ISSUE THREAD

**Issue by mhawksey** [techmeetup/edinburgh#108]
Offering my services as a speaker. I've previously spoken about Google Apps Script https://github.com/techmeetup/edinburgh/issues/88 I've got a new talk I can give on 'The Google Analytics of Things' Kicked the tyres on it once in Liverpool back in June. If you want to get a flavour the original deck is here https://www.slideshare.net/mhawksey/the-google-analytics-of-things-iwmw16 (if something you're interested planning to tweak)

**Comment by marksutherland** [comment]
Hi @mhawksey ,

Normally I'd wait a bit longer before asking someone to talk again, but as it happens we're currently short a speaker in October. Would you be up for speaking on Wednesday? Sorry for the short notice, and thanks for offering to speak again so soon!

**Comment by mhawksey** [comment]
Yep free this Wednesday. Talk description below if you need one:

The majority of websites are using Google Analytics for tracking and reporting (W3Techs report 82.9% of tracked sites are using Google Analytics). Since launching Google Analytics in November 2005 the Internet has radically changed moving away from static content to fully interactive web applications. Google have addressed this with the integration of event tracking and other collection techniques, including deployment within mobile apps. As Google Analytics continues to evolve there are a number of features and use cases you might not be aware of. This presentation is designed to highlight some of the emerging Google Analytics hacks which will hopefully inspire you to look at your analytics problems and opportunities in new ways. For example, we look at how Google Analytics can be used as part of the Internet of Things, using low cost computing like Raspberry Pis for recording and analysing everything from sensor data to physical switches. We also look at bridging offline and asynchronous tracking sending measurement data in batches when connectivity is reestablished as well as pushing data from third party APIs into Google Analytics using free tools.

**Comment by marksutherland** [comment]
Thanks! I'll just publish the talk title, but thanks for the details!. You know what the deal is, so I guess I'll see you on Wednesday! Thanks again!
