### ISSUE TITLE
Edinburgh TechMeetup 12 October 2016

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#109]
## Ship List
- [ ] Email SkyScanner Reception to make sure they're ready for us
- [ ] Open Tech Calendar event ([link to event])
- [ ] Drinks ordered
- [x] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [x] Pizza paid for
- [x] Speakers confirmed (#105, #108 )
- [ ] Confirm volunteer to man the door
- [ ] Confirmed speakers video and internet requirements
- [ ] Website updated ([link to commit])
- [ ] Email announcement sent
- [ ] Confirm organisers present
    - [ ] @rwillmer
    - [ ] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm
    - [ ] @marksutherland

**Comment by marksutherland** [comment]
Only one speaker confirmed so far. Of the two other recent additions to the list, Martin talked in May, and Steve hasn't responded to my comment yet. Will do a bit of chasing up over the weekend.

**Comment by kilbswhitecrow** [comment]
Steve responded by email, and assumed that that would get through. Apologies for not checking back here....

**Comment by rwillmer** [comment]
Rachel checks what happens when you reply to email on a github email
that says you can "reply to this email directly"

My assumption is that it should add this reply as a comment to the
github issue.

Steve Kilbane wrote:

**Comment by marksutherland** [comment]
Hi @kilbswhitecrow,

Dunno what happened there, normally replying to github emails Just Works. Anyway, we're sorted for October now, but if you fancy November that would be great :)

**Comment by marksutherland** [comment]
:ship:ed
