### ISSUE TITLE
Edinburgh Techmeetup 9 November 2016

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/edinburgh#111]
## Ship List
- [ ] Email SkyScanner Reception to make sure they're ready for us
- [ ] Open Tech Calendar event ([link to event])
- [ ] Drinks ordered
- [x] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [x] Pizza paid for
- [ ] Speakers confirmed (#104, ...)
- [ ] Confirm volunteer to man the door
- [ ] Confirmed speakers video and internet requirements
- [ ] Website updated ([link to commit])
- [ ] Email announcement sent
- [ ] Confirm organisers present
    - [ ] @rwillmer
    - [x] @MariusCiocanel
    - [ ] @marshant
    - [ ] @douglasm
    - [x] @marksutherland

**Comment by marksutherland** [comment]
Sigh. Another month where I have the next booked but one short for the current. I have a rough idea for a talk about networking, but I don't think I have time to prepare it for Wednesday. I'll try and rustle up someone but if anyone has leads that would be very helpful.

**Comment by marksutherland** [comment]
James Baster is going to do a short talk on SEO and Allan Lloyds might talk about hackathon/product forge (unconfirmed).

**Comment by marksutherland** [comment]
🚢 ed
