### ISSUE TITLE
Paul Sinclair - esoteric programming languages

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#112]
10 min lightning talk.

**Comment by pbsinclair42** [comment]
Cheers Mark.  Aye, my plan would be to blether for a bit about a few different esoteric programming languages, then go into detail on [JSFuck](http://www.jsfuck.com/) and how JavaScript is designed in such a way that allows it to exist.  It may not be the most useful talk ever given, but hopefully should be a bit of fun!

**Comment by marksutherland** [comment]
Hi @pbsinclair42 , it's looking like we may have enough talks to do a round of lightning talks in January (11th), does that suit you? Thanks!

**Comment by pbsinclair42** [comment]
I'm afraid I'll be in Ireland that week, sorry!

**Comment by marksutherland** [comment]
Bah. We can probably fit a lightning talk in later than the year then. Not entirely sure when would be best yet, I'll let you know when I do. If you fancy talking for longer that would be fine :)

**Comment by pbsinclair42** [comment]
I could probably go into a bit more detail on it all and make it a full talk if you fancied, aye, let me know if that'd suit any month.

**Comment by marksutherland** [comment]
Either is fine. The next few months are on February 8th, March 8th, April 12th and May 10th. February and March are getting busy, so they might be a good fit for a shorter talk. Let me know what suits you best!

**Comment by pbsinclair42** [comment]
February would be fine by me, or if it would suit better to be in March then that should also be fine, beyond that I'd need to wait til closer to the time to check.  Also, I suspect it will be a full length talk at this rate, though there's plenty stuff I could cut no bother if preferred.

**Comment by marksutherland** [comment]
February would be great! And a full talk should be fine :) I'm assuming you're familiar with how TMU usually goes (just ask if not), the main things to know about presenting is that there is HDMI or micro display port available or there's a PC to present from if don't want to use your own device. It's probably best to email me a copy of your slides as a backup by Tuesday, and it would be great if you could let me know of a title for your talk ASAP to help with announcements etc. There's a youtube livestream that is kept up for posterity, so if you'd rather not be recorded let me know and I'll pass it on.

I think that's the key things, let me know if you have any further questions and I'll see what I can do!

**Comment by pbsinclair42** [comment]
My presentation's all on Google Slides so all I'll need is the internet and I should be fine!  No problem with the livestream either.  The current working title is 'Esoteric Programming Languages, and why JavaScript is too clever for its own good'

**Comment by pbsinclair42** [comment]
One wee question actually, what's the recommended min and max talk time?

**Comment by marksutherland** [comment]
I generally recommend about 20-25mins, so questions rounds it out to a half
hour. We can be flexible though if we need to, but I doubt anyone would pay
attention for a full hour full of beer and pizza ;) If you think you need a
little more time, let me know and I'll adjust the schedule to fit.

Mark
