### ISSUE TITLE
Kris Findlay - Lightning Talk

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#116]
Hi @azmodie , still up for a lightning talk? It's looking like January (11th) might be feasible, does that suit you? Any idea what you might be talking about? Thanks for volunteering!

Mark

**Comment by marksutherland** [comment]
Hi @azmodie, just wanted to confirm you're up for doing a lightning talk next Wednesday (11th)? If so, do you have a title for your talk? If you have any slides, it would probably be best to get a copy to me by Tuesday as a backup, but they might not be necessary for a short talk. Hope you had a nice break!

**Comment by azmodie** [comment]
Hi @marksutherland . only just got back from an internet hiatus over the holidays. 
I'm not prepared at all. although will try to through some loose slides/idea on "Cheap and dirty IOT"
Just a brief overview of esp8266 form factors and various tools/ languages available. 

whats the time scale ( 10m talk ? questions ?)

Kris

**Comment by marksutherland** [comment]
Hi Kris, that sounds good to me :) It only has to be about 5-10 mins, we'll probaby have time for a couple of questions afterwards, but I'll try to encourage folk to talk during the break instead. No idea exactly how things will run yet, I suspect we'll make it up on the night. Let me know if you have any questions and I'll see what I can do. Thanks!
