### ISSUE TITLE
Patrick Grant - Lightning Talk

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#117]
Hi @patrickangusjohngrant :) Any idea what you might be talking about? Thanks for volunteering!

Mark

**Comment by marksutherland** [comment]
Hi @patrickangusjohngrant , just wanted to confirm you're up for talking next Wednesday (11th)? If so, any idea what your talke title might be? If you have slides, it would probably be a good idea to send me a copy by Tuesday. Hope you had a nice break!

**Comment by MariusCiocanel** [comment]
assuming this happened
