### ISSUE TITLE
Gordon Guthrie

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#119]
Hi @gordonguthrie , hope you're seeing this. Thanks again for offering to speak. As it stands, it looks like we're booked up this month (probably a bit short notice anyway), and I had planned on having a bunch of lightning talks in January. Would you be up for February (8th)?

https://medium.com/@gordonguthrie/will-the-desert-bloom-for-scottish-tech-f9a11bc3b0ad#.x3a0kfyam

**Comment by MariusCiocanel** [comment]
thanks @gordonguthrie
