### ISSUE TITLE
Kate Ho - Lightning Talk

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#120]
@kateho has offered to give a lightning talk on 'job stories'

**Comment by kateho** [comment]
I'm planning to give a quick overview to the [Jobs to be done framework](https://jtbd.info/) and an explanation of why we should move to writing [job stories instead of user stories](https://jtbd.info/5-tips-for-writing-a-job-story-7c9092911fc9#.n0du4y8gq).

**Comment by marksutherland** [comment]
Hi @kateho , just want to confirm your still up for talking next Wednesday (11th). If you have slides, it would be a good idea to get a copy to me by Tuesday. Any idea what you'd like the talk title to be? Hope you had a nice break!

**Comment by MariusCiocanel** [comment]
I think this happened... I wasn't there that month.
