### ISSUE TITLE
Django Channels: real-time data in Django

### ISSUE THREAD

**Issue by rwillmer** [techmeetup/edinburgh#125]
I'm hatching a talk on Django Channels, which I'll be giving in PyCon Slovakia in March.

March TechMeetup is just before that, so if you have a spare slot....

**Comment by marksutherland** [comment]
Nothing scheduled for then yet so consider it booked :)

**Comment by marksutherland** [comment]
Hello, just confirming you're still up for talking next week. If so, is the issue title still the title for your talk? Let me know if you need anything and I'll see what I can do. Thanks!

**Comment by rwillmer** [comment]
Yes please, could you put me on first please? I fly back in on Tuesday and out on Thursday so I need to plan time on weds carefully

**Comment by rwillmer** [comment]
P.s. thanks for organising

**Comment by marksutherland** [comment]
First it is, no problem :) Looking forward to it!

Mark
