### ISSUE TITLE
Talk about CodeYourFuture Scotland - a coding school for refugees

### ISSUE THREAD

**Issue by kabaros** [techmeetup/edinburgh#127]
My name is Mozafar, I am a Sudanese programmer, I've been working in London for the past five years and recently relocated to Edinburgh.

I've been involved in teaching in a coding school for refugees in London (http://codeyourfuture.co/) where we have a class of refugees that is following a six-months program learning web development with the aim of placing them in Tech jobs by the end of the course. The class is a mix of nationalities and backgrounds, divided equally between women and men, and even though most of them had zero-experience with programming when they started, they are already acquiring skills that could open up great opportunities for them.

Scotland has received 40% of the refugees of the UK last year - much more than its proportion of UK population. We are now in the process of starting our first class in Scotland and we've started the selection process for our students, in parallel to that, we're looking for mentors to teach HTML, CSS, JS, React and Node.

I would like to present to you the project, our background and story in London and what we intend to do in Scotland. Hopefully we will get some of you interested to join us as mentors.

Mozafar scotland@codeyourfuture.co

**Comment by wonmaungthein** [comment]
Hello Mozafar,

Thank you so much for reaching me out and I will be so happy to take part in this fantastic opportunity. However, I would like to inform you that I am still a beginner and I do not know much about coding yet. I am still learning to code through free online resources. I will be happy to join if I can be any help for this project. So looking forward to it. 

Cheers,
Won

**Comment by kabaros** [comment]
Hi @wonmaungthein .. there are many ways you can get involved even if you are not an expert on the subjects. I will present those in the talk if I get to do it, or you can get in touch with me directly.

**Comment by wonmaungthein** [comment]
Hi@kabaros.. Thanks for your message and that's really great. I hope you can start your projects soon in Scotland and especially in Edinburgh. I will be looking forward to it. Could you please tell me how to get in touch with you directly? I am very new here and don't know how to contact you. By the way, I have signed up in "Code your future" website. Now, I am learning HTML and Python. Looking forward to hearing from you soon. 

Cheers,
Won

**Comment by marksutherland** [comment]
Hi @kabaros ,

Thanks for offering to talk! If you haven't been to a TMU before, the next is on February 8th and would be a good chance to get a feel for how it usually goes, to maybe meet in person and to give a quick announcement about the project.

If you want to give a longer (20-25min) talk about it, we have space from April (12th). May is on the 10th and June on the 14th. Do any of these dates suit you?

Thanks again for offering to talk!

**Comment by kabaros** [comment]
Hi @marksutherland , I will come to the next TMU on the 8th, and it would be great if I can be given a chance to make a very quick announcement about our school. We're looking to start our first class by end of March, so April would be late for us. Thanks, Mozafar

**Comment by kabaros** [comment]
@wonmaungthein you can get intouch at scotland@codeyourfuture.co

**Comment by wonmaungthein** [comment]
Hi @marksutherland,

Hope you are fine. May I know what is TMU on the 8th and am I allowed to join the meeting? Looking forward to hearing from you soon.

Cheers,
Won

**Comment by willwright82** [comment]
Hi @wonmaungthein — TMU stands for TechMeetup: Here in Edinburgh they happen every 2nd Wednesday of the month, currently at the SkyScanner HQ. From the website:

> Welcoming anyone involved or working in technology. TechMeetup is a monthly excuse for developers and the tech community around Scotland to meet up and learn new stuff from each other. No name badges, no sales pitches, just informative presentations from your peers and a chance to meet some of the tech community around you. We're not centred around specific languages, technologies or disciplines; we believe there's stuff to learn from mixing everyone together. There's no cost to attend, and food and drink are provided.

The next one if on the 8th of February and you can find more information here: https://opentechcalendar.co.uk/event/4749-techmeetup-edinburgh

**Comment by wonmaungthein** [comment]
@willwright82   Thank you so much for your explanation and I will attend my first TMU on 8th of Feb. See you there..

**Comment by marksutherland** [comment]
Hi @kabaros , we already have a couple of speakers lined up for March, but given the time-sensitive nature we might be able to add another, especially if you can fit it into 10-15 minutes? Either way, you're more than welcome to make an anouncement on Wednesday. Hopefully we can chat about it then?

**Comment by marksutherland** [comment]
Hi @kabaros , thanks for coming along last month. Were you happy with the announcement you gave, or would you still like to give a longer talk about the project? Hope things are going well!

**Comment by kabaros** [comment]
hi @marksutherland, I am happy with the short announcement we made last time, I could come do a longer talk about the class itself in May once we start it.

Things are going pretty well. The students are going through the application process and we got quite few volunteers - 3 of them from the Tech meetup actually. So thanks a lot!

**Comment by kabaros** [comment]
we'd be looking for volunteers in Glasgow, so I will check with the Glasgow folks if I can do a similar short announcement there.

**Comment by marksutherland** [comment]
Hi @kabaros , that's great to hear! Get in touch again if you want to do a bigger talk and we'll get you slotted in somewhere. Best of luck!

**Comment by kabaros** [comment]
Hi @marksutherland .. we're up and running now!

Could we do a talk about our class and our journey so far, in June or July?

**Comment by marksutherland** [comment]
Hi @kabaros ! That would be great, we have space in either month, so which suits you best? June would be on the 14th and July on the 12th. Thanks for getting in touch again!

**Comment by kabaros** [comment]
Hey @marksutherland, either dates is fine. You can decide based on the other talks and let us know.

**Comment by kabaros** [comment]
@marksutherland so let's say June the 14th?

**Comment by marksutherland** [comment]
Hi @kabaros, that would be great, we definitely have space in June. Let me know if you have any questions. There's a PC there and if you want to present from your own laptop there is HDMI and mini display port available. Do you have a title for the talk?
Thanks for offering to speak, I'm looking forward to hearing how you've gotten on :)

**Comment by kabaros** [comment]
@marksutherland  .. no specific title in mind yet, let's say  "CodeYourFuture: the coding school for refugees". We will do the talk as a team - there will be 3/4 of us presenting different parts of what we've done so far.

**Comment by marksutherland** [comment]
Cool, that sounds great! How long do you think you'll need? GIven there's
several speakers we could give you more time than normal to cover
everything rather than squeezing it into 25mins. What do you think?

**Comment by kabaros** [comment]
I think 35 mins (40 mins max) should be fine - is that alright with you?

**Comment by marksutherland** [comment]
That sounds good to me! Looking forward to it :)

Mark

**Comment by kabaros** [comment]
@marksutherland is it happening in Skyscanner btw?

**Comment by marksutherland** [comment]
@kabaros yes, it will be in Skyscanner, same as last time. I'm not sure if
I can make it this month, but one of the other volunteers will get you set
up if I'm not. Let me know if you have any questions!

**Comment by kabaros** [comment]
thanks @marksutherland .. is it ok if we have about an hour for our talk? (Promise it won't be boring)

Also it would be great if you tweet about our talk (our handle is @CodeYourFuture_  , we're hoping this can become the start of linking our project with the Tech scene in Edinburgh

**Comment by marksutherland** [comment]
An hour should be fine, you are the only speakers for the night. I had a
feeling you could do with a little more time :)

I'll see if I can get a tweet sent out for you, normally there's supposed
to be an automatic tweet when the anouncement email goes out, but it
wouldn't have refered to your account.
