### ISSUE TITLE
Edinburgh Techmeetup 8 March 2017

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/edinburgh#129]
## Ship List
- [ ] Email SkyScanner Reception to make sure they're ready for us
- [ ] Open Tech Calendar event ([link to event])
- [x] Drinks ordered
- [ ] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [ ] Pizza paid for
- [x] Speakers confirmed (#123, #125)
- [ ] Confirm volunteer to man the door
- [x] Confirmed speakers video and internet requirements
- [ ] Website updated ([link to commit])
- [x] Email announcement sent
- [ ] Confirm organisers present
    - [ ] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm
    - [ ] @marksutherland

**Comment by marksutherland** [comment]
Dropped the ball on the announcement and website this month, will try and get it done tonight. Sorry!

**Comment by marksutherland** [comment]
Can't make it tonight as Ianthe is sick. Given @rwillmer is one of the speakers, I'm hoping the AV stuff should be covered?
Either way, it might be a good idea to make another appeal for volunteers, we could probably do with an extra body to spread the load and add a bit more redundancy ;)

**Comment by marksutherland** [comment]
🚢 ed!
