### ISSUE TITLE
Edinburgh Techmeetup 10 May 2017

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/edinburgh#131]
## Ship List
- [ ] Email SkyScanner Reception to make sure they're ready for us
- [ ] Open Tech Calendar event ([link to event])
- [x] Drinks ordered
- [ ] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [ ] Pizza paid for
- [ ] Speakers confirmed (<#123, #456 [links to issues]>)
- [ ] Confirm volunteer to man the door
- [ ] Confirmed speakers video and internet requirements
- [ ] Website updated ([link to commit])
- [ ] Email announcement sent
- [ ] Confirm organisers present
    - [x] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm
    - [ ] @marksutherland

**Comment by marksutherland** [comment]
Don't know if I'll make it or not this month. The speaker(s) are the Code Your Future folk who gave an anouncement a few months ago, and will be giving an overview of what they've been up to.
