### ISSUE TITLE
Edinburgh Techmeetup 12th July 2017

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#135]
## Ship List
- [ ] Email SkyScanner Reception to make sure they're ready for us
- [ ] Open Tech Calendar event ([link to event])
- [ ] Drinks ordered
- [ ] Drinks delivered to SkyScanner
- [ ] Pizza ordered
- [ ] Pizza paid for
- [x] Speakers confirmed (#113, #134  )
- [ ] Confirm volunteer to man the door
- [x] Confirmed speakers video and internet requirements
- [ ] Website updated ([link to commit])
- [ ] Email announcement sent
- [ ] Confirm organisers present
    - [x] @MariusCiocanel
    - [ ] @marshant
    - [ ] @douglasm
    - [ ] @marksutherland

**Comment by MariusCiocanel** [comment]
🚢 d!
Thanks :)
