### ISSUE TITLE
James Wiseman - Potential Speaker

### ISSUE THREAD

**Issue by jameswiseman76** [techmeetup/edinburgh#138]
Been planning a talk for some time on programmming words and shared vocabulary. The talk is rather lamely titled 'Magic words for programmers', just because the title 'Programming words that you know but don't know that you know and words that you don't know and don't know that you needed to know' is too long.

It goes through a few common scenarios in programming, and demonstrates that 'there's a word for that'. Rather than try to capture the concept each time, we can use the word.

The idea is that we have a rich vocabulary to call upon, but we often don't, and end up re-inventing the wheel.

**Comment by MariusCiocanel** [comment]
We have speakers lined up for July. Would August or September work for you?

**Comment by jameswiseman76** [comment]
September would prob be better.

**Comment by jameswiseman76** [comment]
Hi, calendar looking quite booked out. If you can cover September, can I push back to October?

**Comment by marksutherland** [comment]
Hi @jameswiseman76 , we should have space in October if you're up for it, sorry I didn't follow up about this month. Am I right in thinking you've been to TMU before? Just wondering so I know what information you need to know about giving a talk :)

cc: @alistairhann

**Comment by jameswiseman76** [comment]
Sorry to mess you around folks. Can I push back again to November? I've been to techmeetup before but not for several years. I gave a talk about 5 years ago on JavaScript static analysis.

**Comment by marksutherland** [comment]
November should be fine, nothing currently scheduled. Thanks for letting us know :) I'll get in touch closer to the date!

**Comment by jameswiseman76** [comment]
Hi again, can we close this off, and I'll come back in the new year? Work and family pressures have meant I've not been able to progress this. Apologies for this.

**Comment by marksutherland** [comment]
Hi James,

That's fine :) Re-open when you're ready or let us know through some other
channel! Thanks!
