### ISSUE TITLE
Steve Kilbane - SPDX

### ISSUE THREAD

**Issue by kilbswhitecrow** [techmeetup/edinburgh#139]
SPDX is gaining traction as a means of describing the open-source licences used in a software distribution, but I'd like to see it gain traction _faster_. :-) Hence, an intro on the topic.

**Comment by marksutherland** [comment]
Sounds good :) Any idea when you'd be available? I think we have space in the September/October timeframe.

**Comment by kilbswhitecrow** [comment]
As far as I can tell, both the September and October dates look free, at present.

**Comment by marksutherland** [comment]
Hi Steve, any chance you might be able to talk next week? We still don't have anyone confirmed and I'm trying to figure out who else might be available. Don't worry if not, I appreciate it's quite short notice.

**Comment by kilbswhitecrow** [comment]
Yep - I confirm I'm good for this coming week.

**Comment by kilbswhitecrow** [comment]
A blurb for you: "SPDX - the Software Package Data Exchange - helps open-source producers and consumers understand which software licences apply to the software they are using, receiving and distributing. And it helps OSS compliance officers sleep better at night."

**Comment by marksutherland** [comment]
Thanks so much! Still haven't heard back from the other potential speakers
so it may just be you. I have a vague recollection that Augusts are
quieter, but Douglas thinks there's no predicting how many folk will turn
up.

I'm not going to be there on Wednedsay unfortunately as I'm up North
visiting my parents. I'll send word to the other organizers though.

Let me know if you need anything and thanks again!

Mark

**Comment by kilbswhitecrow** [comment]
If you can't get other speakers, one option is to have a discussion panel instead. It may be easier to get volunteers for that on short notice.

**Comment by douglasm** [comment]
If you are stuck. I have a talk I did at the Go group this week about using
Go in the browser.

**Comment by marksutherland** [comment]
@kilbswhitecrow organizing more people to do something is never easier, at least not in the short term ;) 
@douglasm if you want to, go for it, but we can just have a single talk and spend more time chatting.

Just about the send the announcement and update the website.

**Comment by douglasm** [comment]
I shall let you decide. I don't mind either way. The talk can always be
kept for when you are stuck, though I am preparing another one on the whole
hiring process and how effective various parts of it are.

**Comment by marksutherland** [comment]
Let's just go with Steve this month then. September is looking much busier, and I think there's enough interest to keep us busy through October towards November.

**Comment by kilbswhitecrow** [comment]
Anyone know whether the projector is widescreen?
