### ISSUE TITLE
Hasan Veldstra: An Introduction to Performance Testing of APIs

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/edinburgh#14]
Hasan mentioned that he can't do August but he might be able to give a talk in September 2014

**Comment by mikemcquaid** [comment]
@hassy Could you do this this month?

**Comment by hassy** [comment]
@mikemcquaid not around, sorry

**Comment by hassy** [comment]
@mikemcquaid I can do May (13/05)?

**Comment by mikemcquaid** [comment]
@hassy Sounds good!

**Comment by MariusCiocanel** [comment]
I'm going to send the announcement email soon. I want to confirm that you're still OK to give the talk @hassy this Wednesday

**Comment by hassy** [comment]
@MariusCiocanel yep :+1:

**Comment by MariusCiocanel** [comment]
@hassy will you need internet/a laptop for your talk? what connector does your laptop have for the projector? Thanks!

**Comment by hassy** [comment]
@MariusCiocanel yes, i'll need a mini-DVI adaptor - wifi is optional

**Comment by MariusCiocanel** [comment]
OK. We'll try to find one for you @hassy

**Comment by MariusCiocanel** [comment]
:ship:d! Sorry for the projector trouble. :+1:
