### ISSUE TITLE
CodeYourFuture talk - December 2017

### ISSUE THREAD

**Issue by kabaros** [techmeetup/edinburgh#145]
We first announced CodeYourFuture - the coding school for refugees - in TechMeetup in February, then we had [a talk](https://youtube.com/watch?v=um1GS3bLQfs) in the summer about the progress of the classes, now we want to wrap up the year with a talk in December by showcasing the students' graduation projects, reflecting on our first class in Scotland, and also bring our students (who are mostly Glasgow-based) for a visit to Edinburgh.

**Comment by marksutherland** [comment]
Hi @kabaros 

So sorry I didn't respond to this sooner!

If you're still interested in doing this, maybe February would be a good month? This would be a year after the initial announcement, and we don't currently have anything scheduled.

Thanks for offering!

**Comment by kabaros** [comment]
hey @marksutherland .. few of us can't make it on that day unfortunately. I will get in touch for another one in the months after.

Thanks, Mozafar

**Comment by marksutherland** [comment]
That's fine. We're probably busy until April so maybe May onwards?

**Comment by kabaros** [comment]
yup - that sounds good. I will get in touch again. Thanks, Mark.
