### ISSUE TITLE
Stephen Meyer - GIS or Cross Platform development

### ISSUE THREAD

**Issue by CaptainDecisive** [techmeetup/edinburgh#146]
I'm thinking it's high time I did a talk at TechMeetup, so need to put a little pressure on myself to get organised. Ideas for a talk would be:

- Something to do with GIS development, maybe a general overview, or recent developments, where things are going?

- Cross platform development. I have experience with Xamarin, so could talk about that or do a comparison of the various cross platform options available today.

I might test the waters with Douglas's group in Falkirk, which would be next February, so then could do a talk at TechMeetup in March.

**Comment by marksutherland** [comment]
Hi @CaptainDecisive 

I think you were settling on talking about GIS after the last TMU? Is March still good for you? We should have space in January and February if you're feeling keen ;)

Thanks for volunteering!

**Comment by CaptainDecisive** [comment]
Hey Mark.
First, a happy new year to you. Second, yup, I've been working on a talk on
GIS over the Christmas break.
I've said I'll give the talk a trial run at Douglas's Falkirk group in
February. So March TechMeetup should give me time to polish if required,
with feedback from Falkirk.

I've been trying to think of a pithy title, because you know that's the
most important part, right ;-)
So when I come up with something I'll let you know in plenty of time.

Cheers Stephen

**Comment by marksutherland** [comment]
Hi @CaptainDecisive , are you still up for speaking in March? Thanks!

**Comment by marksutherland** [comment]
Just to let you know I'm going to assume you're still up for Wednesday, but if you can't make it don't worry about it. You're name will be in the anoucement email and on the website until I know otherwise :) Thanks!

**Comment by CaptainDecisive** [comment]
Hi Mark. Just got back from a weekend away, and rearing to go on Wednesday.
I did the GIS talk at Falkirk last week and it seemed pretty well
received. What duration should I aim for on Wednesday?

Stephen

**Comment by marksutherland** [comment]
20-25 minutes with some time for questions. If you think it'll take a bit longer, let whoever is running things know and they might be able to start things a bit sooner. Glad to hear it went well at Falkirk! Sorry I didn't get in touch sooner, the last month has been a bit hectic with the kids.

There's hdmi and mini display port adapters if you want to present from your own laptop, or there is a PC hooked up  to the projector we can get files onto. If you don't want your talk recorded let Pawel know and he'll turn off the live stream.

Do you have a pithy title I can update the website with?

Any further questions or concerns?

**Comment by MariusCiocanel** [comment]
:ship:d! 👍 Thank you
