### ISSUE TITLE
Daniel Irvine and Sarah Johnston

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#149]
Daniel has offered to speak in April along with his colleague Sarah.

"The topics I usually talk about are mentoring, diversity & inclusion, TDD, clean code, and consultancy in general."

**Comment by marksutherland** [comment]
Urgh, I really should have kept this up to date.

Daniel is going to speak in May with his other colleague Rabea Gleissner. Here are their blurbs:

Secrets of successful mentoring
Daniel Irvine

The idea of mentorship is strongest within the software craft community, which values the idea of apprenticeship. But the concepts within the apprenticeship model are valuable to all technical mentors, not just those who hire apprentices. Knowing how to give feedback, having a set of coding exercises, regular planning and estimating are all invaluable skills. In this talk I’ll look at these and other ideas for how to ensure you give your mentees the best chance of success.

Bio:
Daniel is a software consultant based in London. He's a member of the software craft community and a founder and organizer of Queer Code London. In addition to leading development teams, he's an agile coach and mentor.
Daniel's focus is on building high-quality software. He's big on TDD and pair programming, and as a generalist he's worked professionally with C++, C#, Java, Ruby and JavaScript, although these days he's a Clojure enthusiast. Coding aside, his passion is on nurturing the technical growth of others around him.

—-

Of spies, fakes and friends - help your code lead a double life!
Rabea Gleissner

In this talk I want to show how using test doubles can make your unit testing life a whole lot easier! I'll also clarify what the differences between all those various types of test doubles are and explain when to use which one. I'll show how straight forward it can be to write your own test doubles. This will also help understand better what test frameworks like Jasmine and friends do under the hood.

Bio:
Rabea is a London based software developer working for 8th Light, a software consulting company that specialises in writing clean and maintainable code. In her free time she teaches code newbies, does yoga and knits scarves.

**Comment by MariusCiocanel** [comment]
Is this still on the table for May?

**Comment by marksutherland** [comment]
Yup, I've forwarded the email exchange to you for reference.

⁣Sent from BlueMail ​

**Comment by MariusCiocanel** [comment]
thanks. 🚢 d!
