### ISSUE TITLE
Phil Hale - The whys, why nots and hows of remote working

### ISSUE THREAD

**Issue by philjhale** [techmeetup/edinburgh#151]
Yeah I know, terrible title :-) I've written a blog post on remote working which will be published in a couple of weeks. I think there's enough content to turn it into a talk, I just need a few slides.

**Comment by marksutherland** [comment]
Hi @philjhale ! Thanks for offering to talk. We had someone talk about freelancing a few months ago and I'm pretty sure they covered remote working to some extent. However, we haven't had a talk dedicated to it, so it might not be a problem. We might have space in February or March (both the 14th) if you're up for it. Thanks for volunteering to talk!

**Comment by philjhale** [comment]
No problem. You're right, Robin did cover remote working briefly in his talk. I was planning to dig quite a bit deeper into the subject. To give you an idea of the content, it will be based on this [post](https://engineering.salesforce.com/nerdy-new-years-resolution-rock-at-working-remotely-51debc95b95a). March would be my preference over Feb, given that the Feb meet up is on Valentines day :-)

**Comment by marksutherland** [comment]
March it is then. Looks like you've got plenty of detail to go into and lots of good advice. I'll get in touch closer to the date with more details. Thanks!

**Comment by marksutherland** [comment]
Hi @philjhale , just checking you're still up for talking next week? Are you familiar with how TMU usually runs?

**Comment by philjhale** [comment]
Hi @marksutherland. Yes, I'm all set. Yes, I've been to TechMeetup a few times. I've used Google Slides for the presentation, is that okay? I presume there's a laptop in the room, or somebody bring one and I'll be able to access the slides online.

**Comment by marksutherland** [comment]
There is a PC hooked up to the projector we can get files onto either by downloading or emailing, I imagine google slides should work on it. If you want to use your own laptop there is HDMI and mini display port adapters available.

There's usually a live stream that stays up on youtube afterwards, let me know if you'd rather your talk wasn't recorded.

Is the issue title still the best title for your talk?

Let me know if you have any other questions or concerns.

**Comment by philjhale** [comment]
Thanks, sounds like Google Slides will work 👍 The title of the talk I decided on was simply "Remote working".

**Comment by MariusCiocanel** [comment]
:ship:d! 👍 Thank you
