### ISSUE TITLE
Talk Proposal

### ISSUE THREAD

**Issue by parallax7** [techmeetup/edinburgh#152]
Hello, I would like to talk about Computer Chronicles and the Way Back Machine (archive.org). I have previously given this talk to a small group at the EdLUG back in February.

I would be happy to send you the presentation slides for review, though they would need to be slightly modified for Tech Meetup. The talk itself would probably last 30-40 minutes.

I look forward to hearing from you.

**Comment by marksutherland** [comment]
Hi @parallax7 , this sounds great! Would you be able to talk in April (11th)? If not, we have space in June (13th) or July (11th).

Have you been along to TMU before? Our talks are usually in the 20-30min range, but we can usually start the talks a little earlier if we know they're going to take a bit longer. Might not have much time for questions though.

Can you give me a full name and title for the talk as well?

**Comment by parallax7** [comment]
Hi, I can make the talk got about 30 minutes that is no problem. I have been to Tech Meetup before.

My name is Shehraz Ditta and the talk will be 'Computer Chronicles and the Way Back Machine'. When would you like me to give the talk? Thank you.

**Comment by MariusCiocanel** [comment]
Would this month work for you? the 11th of April?

**Comment by parallax7** [comment]
Yes, the 11th April should be fine. Is there anything you would like me to submit prior to the talk next Wednesday?

**Comment by MariusCiocanel** [comment]
You don't need to send anything before the event but here's some more useful info:

There is a PC hooked up to the projector we can get files onto either by downloading or emailing, I imagine google slides should work on it. If you want to use your own laptop there is HDMI and mini display port adapters available.

There's usually a live stream that stays up on youtube afterwards, let me know if you'd rather your talk wasn't recorded.

Let me know if you have any other questions or concerns

**Comment by MariusCiocanel** [comment]
Thanks for the talk 👍
