### ISSUE TITLE
Cambridge Analytica - big data and politics

### ISSUE THREAD

**Issue by gordonguthrie** [techmeetup/edinburgh#153]
Gordon Guthrie did the electoral computing systems for the SNP way back in 2002/2003/2004/2005 - building out the voter contact platform and campaigning strategies.

Previously in the 1990s he was Treasurer of Scottish Computing For Labour, a Labour Key Seats Computing Officer and worked on Labours 2nd generation electoral computing - including mapping based solutions.

He will talk through past and present American and British political campaigns and how the recent Trump/Brexit campaigns fit in this context with their use of data and micro-targetting.

**Comment by marksutherland** [comment]
Hi @gordonguthrie , how soon can you do the talk? We have space in April on the 11th if you're free.

**Comment by MariusCiocanel** [comment]
Hi @gordonguthrie 

There is a PC hooked up to the projector we can get files onto either by downloading or emailing, I imagine google slides should work on it. If you want to use your own laptop there is HDMI and mini display port adapters available.

There's usually a live stream that stays up on youtube afterwards, let me know if you'd rather your talk wasn't recorded.

Let me know if you have any other questions or concerns

**Comment by MariusCiocanel** [comment]
Thanks for the talk 👍
