### ISSUE TITLE
Greg Sutcliffe - Building communities 

### ISSUE THREAD

**Issue by GregSutcliffe** [techmeetup/edinburgh#163]
Since we've set up https://community.techmeetup.co.uk I figure we should sell it a bit. How about a talk on the wonders of Discourse? I'd be happy to come over and cover it :P

**Comment by GregSutcliffe** [comment]
I did! Thanks for the catch, shouldn't post late at night.

I also didn't add context - the idea of a community forum came out of discussions with Marius, not sure if he's mentioned it more widely. I'm using it in place of a mailing list to organise TechMeetup Stirling, but there's no reason to restrict it to just that...

**Comment by MariusCiocanel** [comment]
Hi @GregSutcliffe. Are you happy with the title I chose for your talk or is there a better title that you think we should use?

**Comment by GregSutcliffe** [comment]
@MariusCiocanel ugh, totally forgot to reply to this. Yes that's fine - I might have gone with something more specific, but it's a bit late to change now :D

**Comment by MariusCiocanel** [comment]
@GregSutcliffe Not too late. I'm preparing the email to send to the mailing list and updating the website. If you have a better title please let me know :)

**Comment by GregSutcliffe** [comment]
Gimme an hour, doing bedtime ATM ;)
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by GregSutcliffe** [comment]
@MariusCiocanel ok how about this?

# Communication Tools For Communities

Communities live or die by their ability to communicate - without it, there's no co-operation. While much communication can be done in person, inevitably there must be some tooling to enable those not present to participate (indeed, for online communities, this is the *only* option). In this talk, I'll cover some of the common tooling choices, along with my thoughts on them ;)

**Comment by GregSutcliffe** [comment]
[techmeetup-2018-expanded.pdf](https://github.com/techmeetup/edinburgh/files/2376403/techmeetup-2018-expanded.pdf)

Slides for tonight

**Comment by MariusCiocanel** [comment]
Thanks. 🚢 d!
