### ISSUE TITLE
Tim Taylor - Artificial Intelligence (AI) and Artificial Life (ALife)

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/edinburgh#165]
"The influence of Artificial Intelligence (AI) and Artificial Life (ALife) technologies upon society, and their potential to fundamentally shape the future evolution of humankind, are topics very much at the forefront of current scientific, governmental and public debate. While these might seem like very modern concerns, they have a long history that is often disregarded in contemporary discourse. Insofar as current debates do acknowledge the history of these ideas, they rarely look back further than the origin of the modern digital computer age in the 1940s-50s. In this paper we explore the earlier history of these ideas. We focus in particular on the idea of self-reproducing and evolving machines, and the potential implications for our own species. We show that discussion of these topics arose in the 1860s, within a decade of the publication of Darwin's The Origin of Species, and attracted increasing interest from scientists, novelists and the general public in the early 1900s. After introducing the relevant work from this period, we categorise the various visions presented by these authors of the future implications of evolving machines for humanity. We suggest that current debates of the co-evolution of society and technology can be enriched by a proper appreciation of the long history of the ideas involved. "

**Comment by MariusCiocanel** [comment]
Hi @tim-taylor, 

Are you still ok with giving the talk above next Wednesday at TechMeetup Edinburgh at Skyscanner?
The talks are usually 20 to 30 min including the questions at the end (if you are happy to answer questions).

**Comment by tim-taylor** [comment]
Hi @MariusCiocanel - yes, I'm still on for next week. That's fine. Tim

**Comment by MariusCiocanel** [comment]
new title is "The Deep Past & Far Future of AI: Prospects and consequences of machines that can 
reproduce and evolve"

**Comment by MariusCiocanel** [comment]
Thanks! 🚢d!
