### ISSUE TITLE
Christoph Zwicker - Xtext

### ISSUE THREAD

**Issue by mikemcquaid** [techmeetup/edinburgh#24]
> Yes, we could give a talk on Xtext if that's interesting to the crowd and hasn't been done yet...
> Tell me if you're interested and for what dates you would need speakers.
> christoph.zwicker@avaloq.com

**Comment by mikemcquaid** [comment]
Christoph has confirmed by email that he'll speak on the (11th February)[https://github.com/techmeetup/edinburgh/issues/46].

**Comment by MariusCiocanel** [comment]
:ship: 'd! Great talk.
