### ISSUE TITLE
Rory Fitzpatrick - How JavaScript Collects Your Garbage

### ISSUE THREAD

**Issue by mikemcquaid** [techmeetup/edinburgh#29]
@roryf said he'd consider doing some JavaScript talk.

**Comment by mikemcquaid** [comment]
@roryf Would you be up for doing this on 14th January (https://github.com/techmeetup/edinburgh/issues/44)?

**Comment by roryf** [comment]
@mikemcquaid unlikely I'll be able to do this for at least the next few months. Sorry dude.

**Comment by mikemcquaid** [comment]
@roryf No worries dude, thanks!

**Comment by mikemcquaid** [comment]
@roryf How about 11th March?

**Comment by mikemcquaid** [comment]
Closing this out for now but give us a shout if you're up for doing this in future @roryf!
