### ISSUE TITLE
Becky Smith - TBC

### ISSUE THREAD

**Issue by mikemcquaid** [techmeetup/edinburgh#33]
@rebkwok said she'd do a talk at some point.

**Comment by mikemcquaid** [comment]
@rebkwok Any chance you'd be able to do anything on the 11th March? No worries if not, just thought I'd check in and see if you have any talks in the pipeline. Thanks!

**Comment by rebkwok** [comment]
No sorry - can't do most Wednesdays now unfortunately

**Comment by mikemcquaid** [comment]
No worries @rebkwok. Might close this out but please give us a shout if there's a Wednesday you can do and/or there's any talks you fancy. Thanks!
