### ISSUE TITLE
Ben Foxall - Using the web for close range interactions

### ISSUE THREAD

**Issue by mikemcquaid** [techmeetup/edinburgh#37]
@benfoxall reached out over email.

**Comment by mikemcquaid** [comment]
@benfoxall Would you be up for doing this on 14th January (https://github.com/techmeetup/edinburgh/issues/44)?

**Comment by mikemcquaid** [comment]
@benfoxall No worries, found someone else, thanks anyway!

**Comment by mikemcquaid** [comment]
@benfoxall Would you be able do to this this month? Thanks!

**Comment by benfoxall** [comment]
@mikemcquaid I can't this month unfortunately - it hits the last day of a sprint.

Does TechMeetup always land on the second Wednesday of each month?  I could work out availability for May and June if so.

**Comment by mikemcquaid** [comment]
@benfoxall It does, yeh. You can check the future dates in OpenTechCalendar.

**Comment by mikemcquaid** [comment]
@benfoxall How does June 10th look for you to do this? Thanks!

**Comment by marksutherland** [comment]
Hi @benfoxall, are you still interested in giving a talk soon? We're looking for another speaker on July 8th, let me know if you're available.

**Comment by marksutherland** [comment]
Hi @benfoxall, we're looking for another speaker in September (the 9th, next Wednesday), would you be interested in talking?

**Comment by marksutherland** [comment]
Hi @benfoxall, can you see these comments? I'm not sure if they're getting through, and I don't have another way to get in touch.
If you can, would you be interested in talking in October (14th) or November (11th)? Thanks!

**Comment by marksutherland** [comment]
Closing as I don't think @benfoxall can see these comments. We can re-open if that's not the case in the future.
