### ISSUE TITLE
Amy Guy - Welcome to the Indieweb

### ISSUE THREAD

**Issue by mikemcquaid** [techmeetup/edinburgh#39]
@rhiaro said she'd be up for speaking at TechMeetup. I've put in some suggested topic based on her PhD but that's not confirmed.

**Comment by mikemcquaid** [comment]
@rhiaro has confirmed by email that she'll speak at the February TechMeetup.

**Comment by mikemcquaid** [comment]
@rhiaro requires wifi and VGA.

**Comment by MariusCiocanel** [comment]
:ship: 'd! The talk was awesome and there was a lot of interest in IndieWeb from the audience.
