### ISSUE TITLE
Kate Ho - Story of Interface3

### ISSUE THREAD

**Issue by mikemcquaid** [techmeetup/edinburgh#41]
@kateho said she's be able to speak in January about Ginsberg (or something else).

**Comment by mikemcquaid** [comment]
@kateho Do you have any internet or non-HDMI video connection requirements? Thanks!

**Comment by kateho** [comment]
nope.

**Comment by mikemcquaid** [comment]
:ship:d! Sorry I couldn't be there @kateho; was both ill and on-call (a bad combination).

**Comment by rwillmer** [comment]
Shame you missed it; Kate was awesome!

Mike McQuaid wrote:
