### ISSUE TITLE
Mike Borozdin - A Code Review is More Useful Than You Think

### ISSUE THREAD

**Issue by mikemcquaid** [techmeetup/edinburgh#42]
@mikeborozdin offered to talk by emailing me privately.

**Comment by mikemcquaid** [comment]
@mikeborozdin Would you be up for doing this on 14th January (https://github.com/techmeetup/edinburgh/issues/44)?

**Comment by mikeborozdin** [comment]
Hi @mikemcquaid,

Yes, sure!

**Comment by mikemcquaid** [comment]
@mikeborozdin Great, thanks! Will put you in.

**Comment by mikeborozdin** [comment]
Thanks @mikemcquaid  :-)

**Comment by mikemcquaid** [comment]
@mikeborozdin Do you have any internet or non-HDMI video connection requirements? Thanks!

**Comment by mikeborozdin** [comment]
Hi @mikemcquaid,

No special requirements. And my laptop has an HDMI port.

**Comment by mikemcquaid** [comment]
Thanks!

**Comment by mikemcquaid** [comment]
:ship:d!
