### ISSUE TITLE
Gordon Watson - Seeing in the dark with Open Source.

### ISSUE THREAD

**Issue by mikemcquaid** [techmeetup/edinburgh#43]
@gcw001, by email:

> 3D Visual Simulations is a small company based in Edinburgh that develops innovative software solutions for the Rail industry.
>
>For our latest project we were approached by Network Rail to find a solution to the problem of
positioning signal lights in dark tunnels. Using data from cameras, laser scanners and 
positioning devices we developed a solution using open source toolkits.
>
> The talk will give an overview of the problems that the project faced and the tools and techniques that we used to solve them.

**Comment by mikemcquaid** [comment]
@gcw001 Could you do this this month?

**Comment by gcw001** [comment]
Sure, I'd be happy to!

Gordon.

**Comment by mikemcquaid** [comment]
Great, thanks!

**Comment by mikemcquaid** [comment]
@gcw001 Do you have any internet requirements for tomorrow night? What video connector will you be using? Thanks!

**Comment by gcw001** [comment]
Hi Mike,

No internet requirements and HDMI please!

Thanks,

Gordon.

**Comment by MariusCiocanel** [comment]
:ship:d! Thanks for the talk!
