### ISSUE TITLE
Meetup Edinburgh: 14 January 2015

### ISSUE THREAD

**Issue by rwillmer** [techmeetup/edinburgh#44]
## Ship List
- [x] Open Tech Calendar event (http://opentechcalendar.co.uk/event/1949)
- [x] Drinks ordered
- [x] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [x] Speakers confirmed (#41, #42)
- [ ] Confirm volunteer to man the door
- [ ] Confirmed speakers video and internet requirements
- [x] Website updated (https://github.com/techmeetup/techmeetup.co.uk/commit/a360ec)
- [x] Email announcement sent
- [ ] Confirm organisers present
    - [ ] @mikemcquaid
    - [ ] @rwillmer
    - [x] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm

**Comment by mikemcquaid** [comment]
Might not be able to make it that evening as I'm on call but will see how the day goes (will come along and hide in the back with a laptop if it's quiet).

**Comment by mikemcquaid** [comment]
:ship:d (and sorry I couldn't be there :cry:)
