### ISSUE TITLE
Meetup 11th February 2015

### ISSUE THREAD

**Issue by mikemcquaid** [techmeetup/edinburgh#46]
## Ship List
- [x] Open Tech Calendar event (http://opentechcalendar.co.uk/event/1950)
- [x] Drinks ordered
- [x] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [x] Speakers confirmed (#24, #39)
- [ ] Confirm volunteer to man the door
- [ ] Confirmed speakers video and internet requirements
- [x] Website updated (https://github.com/techmeetup/techmeetup.co.uk/commit/683236)
- [x] Email announcement sent
- [x] Confirm organisers present
    - [ ] @mikemcquaid
    - [x] @rwillmer
    - [x] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm

**Comment by MariusCiocanel** [comment]
Are we OK to send the email announcement?

**Comment by mikemcquaid** [comment]
@MariusCiocanel Yup. Was gonna do it Monday morning.

**Comment by mikemcquaid** [comment]
Sorry for the last-minute bail but I'm not going to be able to make it tonight due to wife bike issues. Sorry folks :disappointed:

**Comment by MariusCiocanel** [comment]
:ship: 'd! :)
