### ISSUE TITLE
Rachel Willmer - Using Firebase for real-time data in my Django system

### ISSUE THREAD

**Issue by rwillmer** [techmeetup/edinburgh#47]
I'm in the middle of rewriting my entire Luzme website to replace the Django front-end with one based on AngularJS/Firebase. Once it's done (Feb?), I'd like to share my experience (March?)

**Comment by mikemcquaid** [comment]
I'm :+1:  for the talk but will need to double-check on timescale.

**Comment by rwillmer** [comment]
no problem, just can't do it before March cos I won't have the experience to talk about.. but we can leave me as a floating option for later, if you want

**Comment by mikemcquaid** [comment]
Yup, :cool:!

**Comment by mikemcquaid** [comment]
Yeh, March is looking good if you're up for that @rwillmer?

**Comment by mikemcquaid** [comment]
@rwillmer How's 11th March looking?

**Comment by rwillmer** [comment]
Hi Mike

Sorry, I missed this the first time round; been away...

And sorry #2, I won't be ready to do this talk in March; should be ok 
for April though. But I need to finish doing the work that I want to 
talk about so I've got something to say...

Rachel

Mike McQuaid wrote:

**Comment by mikemcquaid** [comment]
@rwillmer How's April looking?

**Comment by rwillmer** [comment]
May would be better...

I could do it in April if you're short of a speaker, but would prefer 
May if that's OK?

Rachel

Mike McQuaid wrote:

**Comment by mikemcquaid** [comment]
@rwillmer Sure, thanks!

**Comment by mikemcquaid** [comment]
@rwillmer April would be best if that's OK?

**Comment by rwillmer** [comment]
Okeydoke.

April it is...

Rachel

Mike McQuaid wrote:

**Comment by mikemcquaid** [comment]
@rwillmer :heart:

**Comment by MariusCiocanel** [comment]
:+1: Thanks for that talk.
