### ISSUE TITLE
Riak, CRDTs and highly available databases healing after partition

### ISSUE THREAD

**Issue by gordonguthrie** [techmeetup/edinburgh#48]
Happy to do a talk at any (or all) of the TechMeetups now that I am a permie at Basho

**Comment by mikemcquaid** [comment]
Thanks @gordonguthrie. We've got a bit of a backlog currently but will keep you in mind. Thanks!

**Comment by douglasm** [comment]
If you are interested in travelling the many miles to Falkirk, we could use you as a speaker at the Falkirk Linux Users Group.

**Comment by mikemcquaid** [comment]
@gordonguthrie How does June 10th look for you to do this? Thanks!

**Comment by marksutherland** [comment]
Hi @gordonguthrie, are you still interested in giving a talk? We're looking for someone to talk on July 8th, would you be available then?

**Comment by marksutherland** [comment]
Hi @gordonguthrie, would be up for speaking in December (9th)? I had hoped to get some folk to make something, but haven't had any confirmations.

Sorry for the short notice, I thought I had sent this last week but just discovered I forgot to hit comment.

**Comment by MariusCiocanel** [comment]
Closing since this is old :)
