### ISSUE TITLE
Election Open Data, 5 min talk, Feb or March 2015

### ISSUE THREAD

**Issue by jarofgreen** [techmeetup/edinburgh#49]
Can do in 5 mins if wanted. Prob up to 10 mins max at this stage.

Covering some great Open Data projects:

http://mapit.mysociety.org/ Geographical data on seats
https://yournextmp.com/ Candidate lists

both of these are based on work with http://poplus.org/ - mySociety are involved, would be interesting to mention.

then http://electionleaflets.org/ project

and then my own project http://meetyournextmp.com/

**Comment by mikemcquaid** [comment]
Might be pushing this for Feb or March unless we jammed it into the notices section somehow?

**Comment by jarofgreen** [comment]
could do, will make 3 or 4 mins if you want for that?

**Comment by mikemcquaid** [comment]
@jarofgreen Yeh, that works for me. Would you need any video or internet?

**Comment by jarofgreen** [comment]
No, just static slides if possible

**Comment by jarofgreen** [comment]
Shall we do 2 days time then?

**Comment by mikemcquaid** [comment]
@jarofgreen Yeh, that's fine with me. We'll just get you set up before the introductions.

**Comment by mikemcquaid** [comment]
@jarofgreen Did this get :ship:d?

**Comment by jarofgreen** [comment]
@mikemcquaid What, the website? Yeah http://meetyournextmp.com/ - already has some activity but needs to ramp up now. Pass on http://meetyournextmp.com/formedia/ to anyone interested - I've already meet a bunch of democracy ppl locally but if you know more happy to chat! There is the Scottish elections next year to if this goes well ....

**Comment by mikemcquaid** [comment]
Oh, I mean the 5m talk :grinning:

**Comment by jarofgreen** [comment]
I did do the talk, yes ... is that what your asking?

**Comment by mikemcquaid** [comment]
Yup, thanks!
