### ISSUE TITLE
Meetup 11th March 2015

### ISSUE THREAD

**Issue by mikemcquaid** [techmeetup/edinburgh#50]
## Ship List
- [x] Open Tech Calendar event (https://opentechcalendar.co.uk/event/1951)
- [x] Drinks ordered
- [x] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [x] Speakers confirmed (#51, #52)
- [x] Confirm volunteer to man the door
- [x] Confirmed speakers video and internet requirements
- [x] Website updated (https://github.com/techmeetup/techmeetup.co.uk/commit/a941a6db46bc571198fd3fb729a435147b2be30b)
- [x] Email announcement sent (https://groups.google.com/forum/#!topic/techmeetup/W8ne_X_MKUw)
- [x] Confirm organisers present
    - [x] @mikemcquaid
    - [x] @rwillmer
    - [x] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm

**Comment by MariusCiocanel** [comment]
:ship:d!
