### ISSUE TITLE
Douglas McCallum - Using Go in the real world

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/edinburgh#53]
@douglasm offered to do a talk if we're ever short on speakers.

**Comment by mikemcquaid** [comment]
@douglasm Any chance you could do this next Wednesday?

**Comment by douglasm** [comment]
I can do it. I did a test run with it at the April EDLUG meeting.

**Comment by mikemcquaid** [comment]
Great, thanks @douglasm. Still seem to be no takers for a second slot. @techmeetup/edinburgh, any ideas? Otherwise I'm happy to do one.

**Comment by douglasm** [comment]
You could give a chap called Calum Gilchrist a nudge, he is on Twitter
as homelinen. He works at Fanduel and has done a couple of talks for us at
the Falkirk Linux Users Group. He has a talk about the extra services AWS
supplies as part of their service as an emergency talk for a FLUG night.

Steve Kilbane, steve@whitecrow.demon.co.uk gave FLUG a very interesting
talk on the representation of floating point in embedded systems.

Both of them are at TM most months.

**Comment by mikemcquaid** [comment]
@douglasm He's on board, thanks!

**Comment by mikemcquaid** [comment]
:ship:d!
