### ISSUE TITLE
Mia Alexiou - An introduction to Swift

### ISSUE THREAD

**Issue by subsymbolic** [techmeetup/edinburgh#54]
The Swift programming language is a huge improvement over Objective C and makes iOS programming faster for existing developers and much more accessible for new developers.

If people are interested in learning more about Swift I'll happily give an intro talk and can do it in either of these formats:
Option 1. An overview of the Swift programming language
Option 2. Developing your first iOS app using Swift

**Comment by mikemcquaid** [comment]
@subsymbolic Sounds great! Would you be able to do this in May? Either 1 or 2 sound good.

**Comment by subsymbolic** [comment]
@mikemcquaid, unfortunately I can't do April, but May and June are both good.

**Comment by mikemcquaid** [comment]
@subsymbolic Cool May would be great.

**Comment by subsymbolic** [comment]
@mikemcquaid That's perfect.

**Comment by subsymbolic** [comment]
It's just dawned on me that this is just before WWDC where Apple will likely be providing new advice on Swift. How do you feel about moving it to July so that I can cover the latest and greatest? I'm still happy to do May if changing at this late stage is too hard.

**Comment by MariusCiocanel** [comment]
I think most people haven't looked at Swift so far. The ones who have will have a good idea about where to get more detailed information. It's up to you but I think May would be better :)

**Comment by subsymbolic** [comment]
May it is then :)

**Comment by MariusCiocanel** [comment]
@subsymbolic will you need internet/a laptop for your talk? what connector does your laptop have for the projector? Thanks!

**Comment by subsymbolic** [comment]
I'll bring my Macbook Pro. Connectors would be great, my laptop has thuderbolt and hdmi ports. Thanks :-)

**Comment by MariusCiocanel** [comment]
:ship: d! Great talk :+1:

**Comment by subsymbolic** [comment]
Thanks :) Is the video available anywhere? I would love a copy if it is.

**Comment by INDIGI-CO-UK** [comment]
Hi Mia! ;) Yes, video will be available tomorrow evening (Thursday). I'll let you know where ;)
