### ISSUE TITLE
Mia Alexiou - Debugging web services with Charles Proxy

### ISSUE THREAD

**Issue by subsymbolic** [techmeetup/edinburgh#55]

**Comment by marksutherland** [comment]
Hi @subsymbolic,

I was going to wait until the new year before getting in touch, but we're a bit short on speakers for December (9th) at the moment, so I'm wondering if you'd be available to talk then?

If not, would be interested in talking in the new year? The first three meetups will be on the 13th January, 10th February and the 9th March. Do any of those suit you?

Thanks for offering to speak again! Hope you're doing well!

Mark

**Comment by subsymbolic** [comment]
H Mark,

I can't do next week but I am free on the 10th of Feb. I'm not sure about this particular topic anymore so I'll come up with some alternatives and run them past you before then.

Mia

**Comment by marksutherland** [comment]
Hi Mia,

That's fine, I had a feeling it was a bit short notice. Don't worry about the topic, I'm sure you'll come up with something great :) Hope you have a nice holiday season!

Mark

**Comment by subsymbolic** [comment]
Hi Mark,

How does "Debugging web services with Charles" sound for my Feb talk? If that doesn't work I can talk about UI testing approaches (but unlike my original idea it will be generic rather than iOS/platform specific).

Mia

**Comment by MariusCiocanel** [comment]
I think "Debugging web services with Charles Proxy" sounds good :)

**Comment by subsymbolic** [comment]
Perfect :)

**Comment by marksutherland** [comment]
What, err, yes, seconded :)

**Comment by marksutherland** [comment]
Hi @subsymbolic ,

I can't make it to the meetup this month, so @douglasm will get you set up with the projector etc. As usual, it's probably a good idea to send a copy of your slides in advance just in case. I don't think much has changed since your last talk, but if you have any questions or requests let us know and we'll see what we can do!

**Comment by subsymbolic** [comment]
Thanks @marksutherland, that all sounds good, I'll send my slides next week.

**Comment by MariusCiocanel** [comment]
:ship:d! Thanks @subsymbolic

**Comment by douglasm** [comment]
We have a new organiser, though she prefers the term helper. I was approached by Miriam, possibly spelled incorrectly, on Wednesday offering to help out. She doesn't have a github account yet, but should be getting one soon.
