### ISSUE TITLE
April 8th

### ISSUE THREAD

**Issue by mikemcquaid** [techmeetup/edinburgh#56]
## Ship List
- [x] Open Tech Calendar event (https://opentechcalendar.co.uk/event/2592)
- [x] Drinks ordered
- [x] Drinks delivered to ~~SkyScanner~~ Appleton Tower
- [x] Pizza ordered
- [x] Speakers confirmed (https://github.com/techmeetup/edinburgh/issues/43, https://github.com/techmeetup/edinburgh/issues/47)
- [ ] Confirm volunteer to man the door
- [x] Confirmed speakers video and internet requirements
- [x] Website updated (https://github.com/techmeetup/techmeetup.co.uk/commit/825c155008971ae757a3b441c2b2cbbed1fd6f8a)
- [x] Email announcement sent (https://groups.google.com/forum/#!topic/techmeetup/5vGsthmq7i4)
- [x] Confirm organisers present
    - [ ] @mikemcquaid
    - [x] @rwillmer
    - [x] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm

**Comment by mikemcquaid** [comment]
I can't make it tomorrow as I'm on-call.

**Comment by MariusCiocanel** [comment]
We have a projector and a screen. Not sure about internet access...

**Comment by douglasm** [comment]
Take in an Ethernet cable and plug it into the wall, if needed.

**Comment by MariusCiocanel** [comment]
:ship:d!
