### ISSUE TITLE
13th May 2015 Meetup

### ISSUE THREAD

**Issue by mikemcquaid** [techmeetup/edinburgh#57]
## Ship List
- [x] Open Tech Calendar event (https://opentechcalendar.co.uk/event/2593)
- [ ] ~~Drinks ordered~~ (We have drinks left over from last month)
- [x] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [x] Speakers confirmed (#14, #54)
- [ ] Confirm volunteer to man the door
- [x] Confirmed speakers video and internet requirements
- [x] Website updated (https://github.com/techmeetup/techmeetup.co.uk/commit/abdeae)
- [x] Email announcement sent
- [ ] Confirm organisers present
    - [ ] @mikemcquaid
    - [ ] @rwillmer
    - [x] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm

**Comment by mikemcquaid** [comment]
I'll probably not be around (get back from :japan: shortly before) so will need someone else to handle the email etc. while I'm away. I'll do the website now.

**Comment by MariusCiocanel** [comment]
I'll send the email when the time comes.

**Comment by MariusCiocanel** [comment]
Done. Had some technical issues with one of the HDMI cables not working but it was all fine in the end.
