### ISSUE TITLE
Calum Gilchrist - AWS: Embracing the Lock-in

### ISSUE THREAD

**Issue by mikemcquaid** [techmeetup/edinburgh#59]
@homelinen mentioned on Twitter that he's up for doing the talk at the June meetup.

**Comment by homelinen** [comment]
@mikemcquaid Settling on: "AWS: Embracing the Lock-in" as a title. 

About a bunch of different "things" as a service you get on AWS. RDS, SQS, DynamoDB, Aurora, Lambda, ELBs, etc.

**Comment by mikemcquaid** [comment]
:+1: sounds great!

**Comment by mikemcquaid** [comment]
@homelinen What are your internet/video adapter requirements? Thanks!

**Comment by homelinen** [comment]
Have a Retina Macbook so a mini-displayport would be great. Would just need access to AWS from the web and command line, for demos. Can work around otherwise. Slides are offline.

**Comment by mikemcquaid** [comment]
Cool, great, have all that!

**Comment by mikemcquaid** [comment]
:ship:d!
