### ISSUE TITLE
July speakers

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#60]
So far I've managed to confirm Christos for July, but most of the other potential speakers in the list either didn't reply or can't make it. I haven't yet asked Mia as she spoke a few months ago.

At this point I guess I have a few options:
* Chase them up again
* Put out a request on twitter or the mailing list
* Ask/beg/~~bribe~~/~~blackmail~~ someone
* Throw together something myself
* Something else?

Any thoughts or advice would be appreciated.

**Comment by marksutherland** [comment]
@MariusCiocanel @mikemcquaid boop.

**Comment by rwillmer** [comment]
How about encouraging a few lightning talks? 5/10 minutes from the floor?

**Comment by MariusCiocanel** [comment]
@marksutherland sorry for the not answering this sooner.
I think having just 1 talk is fine. If the weather is nice we can all go to the pub sooner :)
What do you think?

**Comment by marksutherland** [comment]
I've been pondering this over the weekend and I think I may have a nice solution. Given pretty much everyone I've spoken to has been keen to have some lightning talks, I think we should do these in August, giving everyone a month's notice. We can call it "The Talking Festival!". Well maybe not.

Meanwhile, I can give a talk about giving talks on Wednesday to hopefully inspire and encourage folk to sign up for August, and maybe even get them thinking about doing something bigger later in the year. That keeps us at two talks this month and hopefully sorts out August as well.

What do you think?

**Comment by MariusCiocanel** [comment]
If you're up for giving a talk then sure. Go ahead.
The email template we use is https://github.com/techmeetup/edinburgh/blob/master/AnnouncementEmailTemplate.txt . Feel free to send the email out sometime tomorrow.

**Comment by marksutherland** [comment]
Yeah, I'll focus more on a basic core structure and do's and dont's, and will try and make sure it's all applicable to lightning talks as well.

I'll send out the email tomorrow, thanks for pointing out the template. Is there anywhere else notifications usually go out?

**Comment by MariusCiocanel** [comment]
Check #61 for a checklist. you might want to update the website https://github.com/techmeetup/techmeetup.co.uk/blob/gh-pages/_data/index.json

**Comment by douglasm** [comment]
Greg Sutfcliffe has offered to do a talk on GTD, (Getting Things Done) at some point in the future.

**Comment by marksutherland** [comment]
I've create #62 to track him. Can you add more details and contact information?

Also, I can't seem to add labels, do I need permission, or is there a knack?

**Comment by marksutherland** [comment]
Well that was fun.
