### ISSUE TITLE
Greg Sutcliffe on Getting Things Done

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#62]
@douglasm to provide contact details.

**Comment by douglasm** [comment]
Greg can be contacted at greg.sutcliffe@gmail.com he has done a Foreman talk at TM in the past.

**Comment by marksutherland** [comment]
Emailed Greg to see if he'd be up for talking in September.

**Comment by marksutherland** [comment]
Greg has volunteered to talk in October instead.

**Comment by marksutherland** [comment]
Due to work stuff, Greg has had to reschedule to November.
