### ISSUE TITLE
Andreea Cucu: BioHack

### ISSUE THREAD

**Issue by rwillmer** [techmeetup/edinburgh#63]
Andreea would be interested in doing a talk next month (August)

"I am writing to you on behalf of Edinburgh University's iGEM team. As part of our outreach program, we would like to organize a BioHack in order to encourage Computer Scientists and Biologists to learn from each other and explore different fields. Hence, I would like to give a short talk at this month's tech meetup and speak about why BioHacks are a good idea and why should everyone be excited about them. (and also encourage people to register for our BioHack)"

I'll post their email address on slack.

**Comment by marksutherland** [comment]
I had a chat with Andreea on Wednesday and got the impression she might have wanted to give slightly longer talk than the lightning talks would normally allow. She was also clear that she wanted to talk in August and I guess I can see why now.

**Comment by marksutherland** [comment]
Sent an email to see if she's interesting in discussing how the Biohackathon went in September.

**Comment by marksutherland** [comment]
Confirmed for September.
