### ISSUE TITLE
August Lightning Talks

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#64]
The following wonderful people have already volunteered to give a talk next month:

Geoff Balinger ✓ - IoT == Skynet???
Kyle Bremner ✓ - Short intro to graph databases
@douglasm ✓ - Mr Smug is super smug
@rwillmer ✓
Richard Keen ✓ - Mobile Performance Testing
Tim Willis ✓ - Tusi - fast text entry on your smartwatch
Diwakar ? ✓ 

Haven't heard back from these since last month:

Alex Shaw
John from Upgrade My Spreadsheet
Dr Lapin

The following have offered to swell the numbers if necessary:
James Baster

Given I was looking for around 10 speakers, we're already sorted, but I'll email the list to make sure everyone is aware, and I suspect some may drop out.

Anyway, onto logistics:

* 5min talk
* 2min padding either side
* 3min questions?
* = 10 min each

If we have two blocks of 5, one starting at 7pm, one at 8pm, then we can fit 10 like this, but this means starting the talks considerably earlier than normal. If we drop the questions and start at 7.30, we should be closer to the usual timings.

My plan so far is:
1. Email the list to make sure every one that reads it is aware
2. Email those I have contact details for the thank for volunteering and let them know we'll have more details soon
3. Figure out what those details are
4. Email everyone again a bit later to let them know and get confirmations etc.

Thoughts, comments etc. welcome, particularly about whether we should have questions or not.

**Comment by marksutherland** [comment]
Err, well, I guess I'm doing a bunch of these at once. I think we should start at 7.30 and drop the questions, with the idea being questions can be asked during the break or at the end. I'll ask folk to confirm with a title by next wednesday which will give us a concrete number to work with. I'll worry more about how the evening is going to run over the next week.

**Comment by marksutherland** [comment]
Here's the email I just sent:

Hi Folks!

First, thank you all so much for volunteering to give a talk next month!

Given the high level of interest, we’re going to be quite busy, so the current plan is to have 5 minute talks, with around 2 minutes for turnover and no questions. We will make it clear that any follow up can happen during the break or at the end of the night instead.

With that in mind, it would be great if you could reply to me by next Wednesday (29th) to confirm you’re still up for it. Don’t worry if you’ve changed your mind or you’re busy, we’re always looking for more speakers for future months ;) If you could let me know what the title of the talk is, or what it’s about, that would help as well. Also, if you have particularly strong feelings about when you’d like to talk, please let me know. Finally, feel free to ask any other questions or let me know of any other special requests and I’ll see what I can do.

I’ll get back in touch on Wednesday with further details and to try and set the order for the night.

Thanks again, look forward to hearing from you all!

**Comment by marksutherland** [comment]
@douglasm @MariusCiocanel @rwillmer I either didn't have emails for you, or I wasn't sure if it was correct, so here's hoping github sends you a notification :)

**Comment by marksutherland** [comment]
A couple of folk have dropped out, and a few others have confirmed. I'll chase up those I haven't had a response from. Turns out there's actually 5 weeks betwen TMUs this month so there's a little more time to organize than normal.

**Comment by marksutherland** [comment]
Chased up the stragglers, hopefully a few more will confirm for the 12th.

**Comment by douglasm** [comment]
If you need me to fill in I have a talk I am doing at the Falkirk Linux
Group this month.

Douglas

**Comment by rwillmer** [comment]
I'll do one if you need me to...
Rachel

douglasm wrote:
> If you need me to fill in I have a talk I am doing at the Falkirk Linux
> Group this month.
> 
> Douglas
>

**Comment by marksutherland** [comment]
I've sent another email to the list to try and chase up any stragglers. 

Alistair can't make it, but he's going to try and rustle up someone else from Skyscanner. Tim probably can't make it either, but has offered to talk at a later date.

So, @douglasm, @rwillmer as it stands we could probably do with a few extra talks to fill out the night. Thanks for volunteering and I'm sorry we've ended up here. I'll see if I can rustle up a few others, and hopefully we get one or maybe two from Skyscanner as well.

**Comment by douglasm** [comment]
I gave the talk at the Falkirk Linux User group last night and I know what
to change for TM. I shall be ready

**Comment by rwillmer** [comment]
Put me on early; my talk is about how to overcome being very very shy. I'll ask the floor to come up and have a go; so we might be able to persuade one or two folk to just try it

**Comment by marksutherland** [comment]
Awesome, thanks! Do you have titles for your talks?
@rwillmer are you up for going first?
Alistair has persuaded Richard Keen to talk in his place, we we're up to 5 speakers which seems reasonable.

**Comment by douglasm** [comment]
I don't have a title for mine as because of the subject matter I don't want
to influence people. You could use Mr Smug is super smug.

**Comment by marksutherland** [comment]
Cool. We're up to 7 (Tim is back on and someone got in touch from the last email). Going to update the website and let everyone know the details for Wednesday as well.

**Comment by marksutherland** [comment]
Just sent the following to the speakers:

> Thank you all for offering to give a lightning talk this Wednesday!
> 
> There’s going to be at least 6 talks, possibly more. We’ll do them in two batches with a minute or two for changeover. While we could do one or two of the usual questions, I think it might be better to have 10-15 minutes after each batch for folk to come and chat. Rachel has volunteered to go first, but let me know if you have any preference about when you’d like to speak.
> 
> If you are talking with slides, it would very helpful if you could export them to pdf and reply to this email with them as an attachment. It would also be good if you could take a copy with you just in case. We will try and load up all the slides on one laptop to minimise churn between talks.
> 
> Otherwise, it’s just a case of showing up at 6.30pm on Wednesday at Skyscanner’s offices as usual. I should be fairly easy to find (look for the hairy ginger guy), but there should be a few other organisers who can help if you need it.
> 
> Please let me know if you have any questions and I’ll see what I can do. Look forward to seeing you all,
> Mark

**Comment by douglasm** [comment]
My talk won't work as a PDF, it has an animation in it. I have done it in
OpenOffice and can send it.

**Comment by marksutherland** [comment]
That's fine, I'm installig OO for mac, hopefully the animations will work. Alternatively we could use your device for one of the sessions?

**Comment by douglasm** [comment]
I will be bringing a MacBook, so others can use it.
