### ISSUE TITLE
12 August 2015 Meetup

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/edinburgh#65]
## Ship List
- [ ] Open Tech Calendar event ([link to event])
- [x] Drinks ordered
- [x] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [x] Pizza paid for
- [x] Speakers confirmed (#64)
- [x] Confirm volunteer to man the door
- [x] Confirmed speakers video and internet requirements
- [x] Website updated ([link to commit])
- [x] Email announcement sent
- [x] Confirm organisers present
    - [x] @rwillmer
    - [ ] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm
    - [x] @marksutherland

**Comment by MariusCiocanel** [comment]
I don't think I'll be able to make this one. My wife has a work thing and I have to take care of my daughter.

**Comment by MariusCiocanel** [comment]
I watched the live stream. Great job everyone :+1:

**Comment by marksutherland** [comment]
Glad you enjoyed it! :)
