### ISSUE TITLE
9th September 2015 Meetup

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#66]
## Ship List
- [ ] Open Tech Calendar event ([link to event])
- [x] Drinks ordered
- [x] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [x] Pizza paid for
- [x] Speakers confirmed (#63, see comments)
- [x] Confirm volunteer to man the door
- [x] Confirmed speakers video and internet requirements
- [x] Website updated ([link to commit])
- [x] Email announcement sent
- [x] Confirm organisers present
    - [x] @rwillmer
    - [x] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm
    - [x] @marksutherland

**Comment by marksutherland** [comment]
I still only have one speaker confirmed for next Wednesday. I have a few leads but nothing confirmed which is very frustrating. If anyone knows of someone that can fill in, please let me know, but I appreciate that most of us have done some kind of talking over the last few months.

The good news is that we already have a speaker confirmed for October so it should hopefully be a little easier to get it organized.

**Comment by MariusCiocanel** [comment]
I'll be there on the night but I've been on holiday & really busy with work this last month.

**Comment by marksutherland** [comment]
I've mentioned in the email and on the slack channel that we have space for another speaker, but I doubt we'll get much interest this close. Perhaps this is fallout from so many folk talking last week. I'll make a point of drumming up more volunteers, as I'm not sure how many of the potential speakers are likely to become actual speakers.

**Comment by hammertoe** [comment]
As mentioned just now on Twitter, I'd be willing to do a talk on / around our iOS CI / build system for enquos. Based a bit on blog posts here: https://www.quernus.co.uk/2015/08/15/ios-deployment-part-2/ I could also talk a bit about the enquos project in general, our distributed team and working, quantified health, wearables etc.

**Comment by MariusCiocanel** [comment]
I'm personally interested in quantified self data. @hammertoe I've added you as a speaker. Feel free to edit https://github.com/techmeetup/techmeetup.co.uk/commit/554af664b1857913ea19abd607509f0844c3ddc7 if you want to change the title of your talk.

**Comment by hammertoe** [comment]
OK, great. I don't have edit perms and don't want to fork it just for a minor change so commented on the commit.

One thing to just mention is that I'm flying in from Bristol tomorrow and flight lands at 17:45 so will be hopping in a taxi straight to the venue. Hopefully should be there for the 18:30 start, but just so you know, if anything happens might be a bit late. Mia will be there, and if I'm late I'll let her and you know.

**Comment by MariusCiocanel** [comment]
Talks start closer to 8PM. You could do the second talk so you don't have to hurry.

**Comment by hammertoe** [comment]
OK, great! Yes, please put me on the 2nd talk.

**Comment by marksutherland** [comment]
@hammertoe thanks again for volunteering! If you have a chance, could you email a copy of your slides or stick them online somewhere, just in case? Hope you have a good journey!

**Comment by hammertoe** [comment]
No problem :) Thanks for having me! I must be crazy volunteering to do a talk this last minute ;) But will be fine. Most of the talk content is based on a series of blog posts I've written recently, so fresh in mind. I'll be writing the slides this evening and tomorrow, don't worry... will be regularly syncing to dropbox. I may need to borrow a thunderbolt -> VGA adapter if I can't find mine in time... otherwise will have keynote and pdf files as backup on memory stick.

**Comment by marksutherland** [comment]
There's plenty of thunderbolt adapters there, and I should have one with me as well. FYI it's an HDMI set up, but that shouldn't matter if you've got a thunderbolt port :)

**Comment by hammertoe** [comment]
Great! See you tomorrow.

-Matt
