### ISSUE TITLE
14th October 2015 Meetup

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#68]
## Ship List
- [ ] Open Tech Calendar event ([link to event])
- [x] Drinks ordered
- [x] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [x] Pizza paid for
- [x] Speakers confirmed (#69)
- [x] Confirm volunteer to man the door
- [x] Confirmed speakers video and internet requirements
- [x] Website updated ([link to commit])
- [x] Email announcement sent
- [ ] Confirm organisers present
    - [ ] @rwillmer
    - [x] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm
    - [x] @marksutherland

**Comment by marksutherland** [comment]
Greg had to drop back to November and Pol Clement-Smith from the ORG has offered to speak in November as well. Unfortunately that leaves October empty at the moment. We still have 2 and a bit weeks, but what I could really do with is leads. I'm going to reply to the call for speakers thread on the google group, but if anyone has any suggestions please let me know!

**Comment by marksutherland** [comment]
That's one speaker, I'll try and chase up another.

**Comment by douglasm** [comment]
I have ordered the drink, it should be delivered to Skyscanner on Tuesday. There is a chance I won't be there or able to order pizza. I shall know at the weekend.

**Comment by marksutherland** [comment]
Don't think was meant to be closed.

**Comment by marksutherland** [comment]
We may be getting a talk from Konstantin Kudryavtsev on Ethereum, last minute addition in the wake of a Bitcoin meetup happening tomorrow evening.

**Comment by MariusCiocanel** [comment]
:shipit: .
