### ISSUE TITLE
Scaling MYSQL write performance by adding caching layers for InnoDB

### ISSUE THREAD

**Issue by masoodfanduel** [techmeetup/edinburgh#72]
Scaling writes in MYSQL have always been of interest to both developers and DBA's likewise. Though MYSQL do not provide any in-built solutions that we can use to scale write operations. Though one may argue MYSQL NDB Cluster scaling capabilities but it is not Traditional Innodb style database, it is more of a clustering solution.

In my talk I can discuss introducing NOSQL caching layers for Innodb that we can use to offload intensive write workloads and still able to use SQL. I would also discuss alternative technologies/engines available in market to be used with MYSQL for write scaling.

**Comment by marksutherland** [comment]
Hi @masoodfanduel ! How soon would you be able to talk? We've had a late cancellation in November, so there's space if you're up for it!

**Comment by masoodfanduel** [comment]
Hi,

I can give presentation this month aswell, please let me know which day 
I need to do it as I would need couple of days to prepare.

Thanks

Masood

**Comment by marksutherland** [comment]
Hi Masood,

We've been very lucky to catch Quinn Norton while she's visiting Scotland so we're ok for November, so there's no rush for this month. I'm not quite sure what will be happening in December (9th) as there might be a show and tell thing instead, but if not we'll definitely need speakers then or in the new year. Do either of those options suit you? Thanks,

Mark

**Comment by marksutherland** [comment]
Hi @masoodfanduel,

I haven't really had much interest in the show and tell stuff for December, so if you're still up for talking that would be great. It'll be on the 9th. Are you available then?

Thanks,
Mark

**Comment by masoodfanduel** [comment]
Hello,

I am stuck with some production work so probably couldn't make it in 
December.

Regards,

Masood

**Comment by marksutherland** [comment]
Hi Masood,

Thanks for getting back. Would January or February be more convenient? Best of luck with your work!

Mark

**Comment by marksutherland** [comment]
Hi @masoodfanduel , are you still interested in giving this talk? If so, any chance you'd be up for doing it this Wednesday? Don't worry if not! Thanks again for volunteering!

**Comment by MariusCiocanel** [comment]
this is old. Closing.
