### ISSUE TITLE
Greg Sutcliffe

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#75]
Greg spoke in November 2015 and enjoyed it so much he immediately offered to talk again. WIll likely need plenty of notice as it's a fairly big commute for him.

**Comment by marksutherland** [comment]
Greg has offered to speak in July about Foreman.

**Comment by GregSutcliffe** [comment]
Just adding a +1 here, I'd love to do July - it's Foreman's 7th birthday on that very night. Let me know as soon as I can confirm the event on our community calendar :)
