### ISSUE TITLE
9th December 2015 Meetup

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#78]
- [ ] Open Tech Calendar event ([link to event])
- [x] Drinks ordered
- [x] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [x] Pizza paid for
- [x] Speakers confirmed (#79, James Baster)
- [x] Confirm volunteer to man the door
- [x] Confirmed speakers video and internet requirements
- [x] Website updated ( techmeetup/techmeetup.co.uk@b51349ba86fd808c7dad45376cfb9d580c8910d5 )
- [x] Email announcement sent
- [x] Confirm organisers present
    - [ ] @rwillmer
    - [x] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm
    - [x] @marksutherland

**Comment by marksutherland** [comment]
As it stands, despite some folk voicing interest last month and the month before, I don't have any confirmations for the festive hack-a-thing. If folk show up with something we can make time for it, but I'm not counting on it.

Unfortunately, I also don't have anyone booked yet (Masood is busy, much of the rest of the list either talked recently, aren't available or aren't ready yet.) If anyone knows someone who'd be up for speaking, let me know and I'll get in touch with them. Meanwhile I'll chase up anyone else I can. I'm sure it'll come together as usual...

**Comment by MariusCiocanel** [comment]
Maybe it would be worth tweeting out from the TechMeetup account saying we're looking for speakers?

**Comment by marksutherland** [comment]
Yup, I thought about it last night but I think I was put off (i.e. distracted) by the Syria vote chat. Here's a tweet I've just issued on my own account, I don't think I have credentials for the main TMU account:

https://twitter.com/marksutherland/status/672489350358278144

**Comment by marksutherland** [comment]
Andra (#79) and James will speak on wednesday, though James' may be a little shorter than usual.

**Comment by marksutherland** [comment]
:ship:ed
