### ISSUE TITLE
13th January 2016 Meetup

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#81]
## Ship List
- [ ] Open Tech Calendar event ([link to event])
- [x] Drinks ordered
- [x] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [ ] Pizza paid for
- [x] Speakers confirmed (#70,#80)
- [ ] Confirm volunteer to man the door
- [ ] Confirmed speakers video and internet requirements
- [x] Website updated (techmeetup/techmeetup.co.uk@4114552)
- [x] Email announcement sent
- [ ] Confirm organisers present
    - [ ] @rwillmer
    - [x] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm
    - [ ] ~~@marksutherland~~

**Comment by marksutherland** [comment]
I can't make it in January as I have an antenatal course to attend. We have one speaker confirmed already, I'll chase up another and update.

**Comment by marksutherland** [comment]
Email sent and website updated.

Sadlly I'm not going to be able to make the next TMU either, and probably not the one after as my wife is due on the 8th March. After that I'm not sure what my situation will be, but at the moment I'd hope to be able to come along.

For the moment I can keep contacting and arranging speakers, but somebody else will have to handle the AV stuff and making sure they make it to the venue etc. Also I won't be there to harra^wask people to talk in the future so it would be great if everyone who can make it can try and chase up some leads and create tickets. It may also be a good idea to put out a request for volunteers as it's the start of a new year.

Hope it goes well!

**Comment by MariusCiocanel** [comment]
I'll be there. Hopefully I won't forget to ask people to volunteer to talk at future events :)

**Comment by rwillmer** [comment]
Not sure if I'll be there or not, and I'll definitely miss the one in Feb.

**Comment by MariusCiocanel** [comment]
:ship: d!
