### ISSUE TITLE
Linux on the Desktop

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/edinburgh#82]
@jriddell to give a talk at some point

**Comment by marksutherland** [comment]
Hi @jriddell,

Sorry I haven't been in touch earlier to confirm, but as I understand you're lined up to speaking on Wednesday. Is that ok? If so please let me know if you have any questions! We probably have a back up if you can't make it, and again, sorry I'm only confirming this just now, I should have gotten in touch earlier. Thanks,

Mark

**Comment by marksutherland** [comment]
Confirmation acquired via email.
