### ISSUE TITLE
Edinburgh Techmeetup 09 March 2016

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/edinburgh#85]
## Ship List
- [ ] Email SkyScanner Reception to make sure they're ready for us
- [ ] Open Tech Calendar event ([link to event])
- [x] Drinks ordered
- [ ] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [x] Pizza paid for
- [x] Speakers confirmed (#82, #87 )
- [ ] Confirm volunteer to man the door
- [x] Confirmed speakers video and internet requirements
- [x] Website updated ([link to commit])
- [x] Email announcement sent
- [ ] Confirm organisers present
    - [x] @rwillmer
    - [ ] ~~@MariusCiocanel~~ (away on a work trip for the week)
    - [ ] @marshant
    - [x] @douglasm
    - [ ] @marksutherland

**Comment by MariusCiocanel** [comment]
Created this issue early because I think I might be away on a work trip that week. I'll update the issue when I know more.

**Comment by MariusCiocanel** [comment]
Also one of the talks is #82

**Comment by rwillmer** [comment]
This looks really interesting. And I'll even be here!

**Comment by marksutherland** [comment]
:ship:ed!

Hope it was a good one!
