### ISSUE TITLE
Alistair Hann - From 26 to 2.6 million releases in a year

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/edinburgh#86]
"From 26 to 2.6 million releases per year”
 
As Skyscanner scaled from an engineering team of 30 with one website and three services to a team of 100 engineers, release frequency halved. This is the story of the turnaround as the company went on to grow to 400 engineers, with over 100 services, releasing at hundreds of times the previous rate. The next goal is 10,000 releases per day – this talk will share how we are approaching that and the implications for our tooling, processes, and how we think about writing software.
 
Alistair mentioned he could give this talk in March #85

**Comment by marksutherland** [comment]
Alistair said he was willing to be a short notice fill in. Given we have #82 and #87 already set up for March, we can keep him in the bag for later.

**Comment by rwillmer** [comment]
Really looking forward to that talk by Alastair, it sounds terrific

**Comment by marksutherland** [comment]
:ship:ed
