### ISSUE TITLE
Martin Hawksley, AppScript

### ISSUE THREAD

**Issue by rwillmer** [techmeetup/edinburgh#88]
Martin is the other Google Developer Expert in Scotland; he's volunteered a talk on AppScript

**Comment by marksutherland** [comment]
Awesome, what's the best way to contact him?

**Comment by rwillmer** [comment]
Hmm, I thought he'd subscribed to this ticket. I'll DM you rather than posting it here

**Comment by mhawksey** [comment]
I'm here m.hawksey@gmail.com ;)

**Comment by marksutherland** [comment]
Hi @mhawksey , are you interested in talking this month on the 13th? If not, would May (11th) or June (8th) suit better? Thanks for offering to speak!

**Comment by mhawksey** [comment]
Hi @marksutherland - busy this month organising my own event but 11th May is good for me. Let me know if there is anything you need from me. Thanks :)

**Comment by marksutherland** [comment]
That sounds great to me! I'll get in touch around this time next month to sort things out. Hope your event goes well!

**Comment by jarofgreen** [comment]
Hello @mhawksey - I'll be the guest presenter this month! Just about to email to sort details for the talk.

**Comment by marksutherland** [comment]
:ship:ed
