### ISSUE TITLE
Radek Ostrowski, Finding the perfect weather with Apache Spark, Docker and IBM Bluemix

### ISSUE THREAD

**Issue by radek1st** [techmeetup/edinburgh#89]
I could talk about my recent hackathon winning project:
http://devpost.com/software/my-perfect-weather

**Comment by marksutherland** [comment]
Hi @radek1st ! This looks like a neat project, congrats on winning the prize! Would you be interested in talking about this on the 13th? If not, would May (11th) or June (8th) suit you better? Thanks for offering to talk!

**Comment by radek1st** [comment]
May 11th is better for me. Cheers

On Sat, Apr 2, 2016 at 4:28 PM, Mark <notifications@github.com> wrote:

> Hi @radek1st <https://github.com/radek1st> ! This looks like a neat
> project, congrats on winning the prize! Would you be interested in talking
> about this on the 13th? If not, would May (11th) or June (8th) suit you
> better? Thanks for offering to talk!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/techmeetup/edinburgh/issues/89#issuecomment-204737543>
>



-- 
Radek

**Comment by marksutherland** [comment]
Heh, so somehow I've ended up with 3 speakers for May now :) Would you be able to speak in June or July (13th) instead? Thanks!

**Comment by radek1st** [comment]
Hi, I'll let you know at the end of next week.

**Comment by marksutherland** [comment]
Thanks @radek1st !

**Comment by radek1st** [comment]
Hi @marksutherland you can put me down on 8th of June. Cheers

**Comment by radek1st** [comment]
Hi @marksutherland just to let you know that I'm no longer available for 8th of June. Cheers

**Comment by marksutherland** [comment]
Hi @radek1st , sorry to hear that. Would you be interested in talking in July (13th) or August (10th) instead?

**Comment by marksutherland** [comment]
Hi @radek1st , any chance you could speak on Wednesday? Sorry for the short notice, don't worry if it's not suitable. Thanks for volunteering again!

**Comment by radek1st** [comment]
Sure, I can do that. How much time do I have? 30 min?

**Comment by marksutherland** [comment]
Yeah, maybe more like 25mins with time for questions. Thanks so much for stepping in! I'll use "Finding the perfect weather with Apache Spark, Docker and IBM Bluemix" as the title of the talk. If you can point me at a copy of your slides by Tuesday night as a backup, that would be great, you should probably take a copy with you as well. Skyscanner have a decent AV setup, so if you want to use your own laptop there's mini display port and hdmi inputs available. I'm guessing you're aware of how the night usually goes? If not, let me know, and if you have any other questions or requests I'll see what I can do.

Thanks again!

**Comment by radek1st** [comment]
I've never been to this meetup before, what's the audience like in general? Here's a slide deck I'll use: https://docs.google.com/presentation/d/1fiPW2OPkRmdodFA9Jo1KenGk8M6WO8xssj60xsCUkLk/pub?start=false&loop=false&delayms=3000

**Comment by marksutherland** [comment]
Ah, cool!

The audience is pretty mixed, though fairly technical. Everything from front end to back end to systems, web, enterprise, finance, etc. We often have attendees who work at Amazon, Toshiba (Canon now), SkyScanner, FanDuel, TescoBank etc. As a rule of thumb, it's common for code to appear on the screen at some point, but not always.

The night usually goes like this: Folk start arriving at 6.30pm and there's free drink and pizza and an opportunity to chat and gossip. At 7.30pm we do a round of introductions where everyone gets a chance to say who they are and why they've come along. There's then a break, followed by the first talk and some questions, then another break before the last talk. We're usually done by 9pm and tidy up and head to the pub.

I hope this helps answer some questions, let me know if you have any more!

**Comment by radek1st** [comment]
OK, I should be there at around 7pm, hopefully there will be some beer and pizza left!

**Comment by MariusCiocanel** [comment]
:ship:d!
