### ISSUE TITLE
Graeme Arthur: iPhone Development

### ISSUE THREAD

**Issue by mikemcquaid** [techmeetup/edinburgh#9]
I'd spoke to @graemeearthur about potentially talking on iPhone development at TechMeetup.

**Comment by marksutherland** [comment]
Hi @graemeearther, are you still interested in giving a talk? We're looking for someone else to talk on July 8th if you're available.

**Comment by GraemeEArthur** [comment]
Hi Mark, Unfortunately I'm busy on the 8th but may be up for a talk in the future. Will let you know if I can come up with something.   Cheers, Graeme

---Sent from Boxer | http://getboxer.com

On 27 June 2015 at 00:08:05 BST, Mark <notifications@github.com> wrote:Hi @graemeearther, are you still interested in giving a talk? We're looking for someone else to talk on July 8th if you're available.  —Reply to this email directly or view it on GitHub.

**Comment by marksutherland** [comment]
Hi Grame, thanks for getting back. The next two TMUs are on August 12th and September 9th, would either of those be more suitable?

**Comment by marksutherland** [comment]
Hi Graeme,

Are you still up for doing a talk? We're looking for another speaker in September (9th, next Wednesday) if you're interested?

**Comment by GraemeEArthur** [comment]
Hi Mark,

I’m away on holiday tomorrow and get back next Tuesday. I don’t think I’ll feel too comfortable writing and preparing a talk in that little time I’m afraid.

-- 
Graeme Arthur
Sent with Airmail

On 1 September 2015 at 21:59:06, Mark (notifications@github.com) wrote:

Hi Graeme,

Are you still up for doing a talk? We're looking for another speaker in September (9th, next Wednesday) if you're interested?

**Comment by marksutherland** [comment]
Hi Graeme,

No that seems a bit tight ;) Fancy October? Hope you have a nice holiday!

**Comment by marksutherland** [comment]
Hi @GraemeEArthur, 

Are you up for talking in the new year some time? We have space for speakers on the 13th January, 10th February and the 9th March if so. Hope you're enjoying the festivities!

Mark

**Comment by mikemcquaid** [comment]
@graeme Moved to Berlin unfortunately!
