### ISSUE TITLE
Jamie Apted - Tech Lawyer

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#90]
Jamie offered to give a talk on the legal side of of developing, eg starting a startup or something legal based. 

jamie.apted AT mbmcommercial.co.uk

**Comment by marksutherland** [comment]
Jamie is willing to talk in May.

**Comment by jarofgreen** [comment]
Emailed Jamie

**Comment by marksutherland** [comment]
:ship:ed
