### ISSUE TITLE
Edinburgh TechMeetup 13 April 2016

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#92]
## Ship List
- [ ] Email SkyScanner Reception to make sure they're ready for us
- [ ] Open Tech Calendar event ([link to event])
- [x] Drinks ordered
- [x] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [x] Pizza paid for
- [x] Speakers confirmed (#91, #86 )
- [ ] Confirm volunteer to man the door
- [x] Confirmed speakers video and internet requirements
- [ ] Website updated ([link to commit])
- [x] Email announcement sent
- [ ] Confirm organisers present
    - [ ] @rwillmer
    - [x] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm
    - [ ] @marksutherland

**Comment by marksutherland** [comment]
I thought I would be able to make it, but it looks like I'll be busy :( Can anyone volunteer to be the point of contact for the speakers? Alistair should be easy enough, it's just Gavin that might need a hand.

**Comment by MariusCiocanel** [comment]
I'll greet Gavin.

**Comment by MariusCiocanel** [comment]
:ship: d !
