### ISSUE TITLE
Edinburgh Techmeetup 11 May 2016

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/edinburgh#93]
## Ship List
- [ ] Email SkyScanner Reception to make sure they're ready for us
- [ ] Open Tech Calendar event ([link to event])
- [x] Drinks ordered
- [x] Drinks delivered to SkyScanner
- [ ] Pizza ordered
- [ ] Pizza paid for
- [ ] Speakers confirmed (<#123, #456 [links to issues]>)
- [ ] Confirm volunteer to man the door
- [ ] Confirmed speakers video and internet requirements
- [ ] Website updated ([link to commit])
- [ ] Email announcement sent
- [ ] Confirm organisers present
    - [ ] @rwillmer
    - [ ] ~~@MariusCiocanel~~ (away on holiday)
    - [ ] @marshant
    - [ ] ~~@douglasm~~(away on holiday) 
    - [ ] @marksutherland

**Comment by MariusCiocanel** [comment]
Bela https://twitter.com/ecobela offered to help for the first part of the event (until the talks start)

**Comment by jarofgreen** [comment]
@MariusCiocanel How does one email the reception? Can you hook me into this? Thanks!

**Comment by douglasm** [comment]
Their e-mail is Edinburgh.Reception@skyscanner.net It is normally Ewa who
answers.

**Comment by jarofgreen** [comment]
@douglasm Emailed, thanks

**Comment by jarofgreen** [comment]
@MariusCiocanel @douglasm Do I have to do anything about filming? Ta

**Comment by MariusCiocanel** [comment]
Paweł ( @INDIGI-CO-UK ) should be along to record and live stream the event

**Comment by jarofgreen** [comment]
Great, Thanks! See you later @INDIGI-CO-UK

**Comment by jarofgreen** [comment]
@MariusCiocanel @douglasm Can one of you update the website for me? Thanks.
```

  "edinburgh": {
    "speakers": [
      {
        "name": "Martin Hawksey",
        "talk": "Google Apps Script: The Authentic{ated} Playground"
      },
      {
        "name": "Jamie Apted",
        "talk": "3 Legal pitfalls every tech start-up should avoid!"
      }
    ],
    "day": "11th",
    "month": "May"
  },

```

**Comment by marksutherland** [comment]
:ship:ed
