### ISSUE TITLE
Mike McQuaid

### ISSUE THREAD

**Issue by MikeMcQuaid** [techmeetup/edinburgh#94]
Hello again 👋 

I'm up for doing a talk on either running a successful open-source project or how we work at GitHub (whichever would be most interesting).

**Comment by marksutherland** [comment]
Never heard of it, are you sure this is suitable for TMU? ;)

That aside, either sounds good, which do you think would be more interesting? Is the "successful open-source project" homebrew or something else?

**Comment by marksutherland** [comment]
Oh, also, when? I think there's a space in June (8th), and July (13th) and August (10th) are unbooked at the moment.

**Comment by MikeMcQuaid** [comment]
@marksutherland The principles come from Homebrew but it's a more generally focused talk. I think either would be interesting; depends whether we reckon we have more focused interested in improving their open source projects or their companies (I'd probably guess the latter?)

June 8th works for me.

**Comment by marksutherland** [comment]
Perfect. We had someone booked who had to drop out so it would be great if you could speak next week :)

I think you're probably right that more folk might be interested in the latter, but maybe they'll be pleasantly surprised at what they learn from the former ;) If it helps, the other talk will be about the Scottish Government's Digital Directorate.

FYI, we're temporarily relocating to Codebase's event space this month, which is round the back of Argyle House. I'm sure you know all the other details, very little has changed :)

**Comment by MikeMcQuaid** [comment]
June 8th it is. Happy to do the other talk if you're ever struggling for speakers in future.
