### ISSUE TITLE
Edinburgh TechMeetup 8 June 2016

### ISSUE THREAD

**Issue by marksutherland** [techmeetup/edinburgh#96]
## Ship List
- [ ] Email SkyScanner Reception to make sure they're ready for us
- [ ] Open Tech Calendar event ([link to event])
- [x] Drinks ordered
- [ ] Drinks delivered to CodeBase
- [x] Pizza ordered
- [x] Pizza paid for
- [x] Speakers confirmed ( #94, #95 )
- [ ] Confirm volunteer to man the door
- [ ] Confirmed speakers video and internet requirements
- [ ] Website updated ([link to commit])
- [ ] Email announcement sent
- [ ] Confirm organisers present
    - [ ] @rwillmer
    - [x] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm
    - [ ] @marksutherland

**Comment by MariusCiocanel** [comment]
🚢d!
