### ISSUE TITLE
Wedding rings, curves and coastlines

### ISSUE THREAD

**Issue by danielphil** [techmeetup/edinburgh#97]
Hello,

Just following up on chat I had with @marksutherland and @MariusCiocanel about a potential talk I could do at a future Techmeetup. I'm not sure if this is the kind of thing that you think would be appropriate for Techmeetup: I could also base a talk around Typescript or Three.js, but I'd need to prepare the talk for that, so it would take me a bit longer.

### Overview
I’ve been working on a side project to resample images along a curve in an attempt to recreate the design on my wedding ring. In the process, I learned some stuff, made a simple demo and thought that others might find it interesting if I was to give a quick summary.
 
In the talk, I’ll be covering:

- What’s a wedding ring got to do with this anyway?
- Some ways of representing curves and how to draw them
- How to resample an image along a curve
- A live demo (eek!) where I attempt to roughly recreate the design on the ring
 
I used quite a lot of things in the making of the demo (Three.js, GLSL, TypeScript, etc.), but I’m not really going to cover those topics in much detail at this talk. (But I can organize a followup talk if people think this would be interesting) The content is pretty straightforward, so if you’ve done some maths in school you should be fine. 🙂

I've got some slides for the talk here: https://www.dropbox.com/s/tzjjajpv28w88nr/Curves.pptx?dl=0
(Sorry, they're in super-uncool Powerpoint format. Let me know if you need to export as a PDF for opening them) Might add a few little tweaks, but these are mostly what I'd use to present.

**Comment by marksutherland** [comment]
Hi @danielphil , thanks for volunteering! Overall I think this would be a great talk for TMU. The only thing I can think of is that it might be worth talking more about the technologies you've used, as it's a great example of you can integrate different things together to achieve a greater whole. That said, doesn't need to be much more than explaining a little more about what they are and how you utilized them.
But it's your talk :) Even as it is I'm sure it'll go down well.
When would you be able to give it? July's TMU is on the 13th, August on the 10th and September's on the 14th.
Thanks again!

**Comment by danielphil** [comment]
Hello! That sounds like a good idea- it would help broaden the talk out a bit and maybe make it more appealing to a wider audience. I'll have a look through the talk and rejig it to include more about how I used TypeScript and Three.js to put it all together. Just to check- is there a time limit for the talk that I should aim for?

Is it OK if I give the talk in the August slot?

**Comment by marksutherland** [comment]
Hi @danielphil , 

Time limit is around 20-25mins, which lets us get the talk and questions done in about half an hour.
We stil have space in July if you think you'd be ready, otherwise, August is fine. Thanks again!

**Comment by danielphil** [comment]
Hi @marksutherland,

That's great- thanks! Alas, I can't do this month, but August will be fine. Sorry for the confusion! I'll run through a talk a few times and will make sure it fits in the time.

**Comment by marksutherland** [comment]
Hi @danielphil , just want to confirm you're still up for talking next week?

I know you're a regular, so I'll spare you most of the details, but the key things to know is that there is hdmi and mini display port inputs available if you want to present from your own laptop, there's a PC with windows and powerpoint etc. if not and it's probably a good idea to email me a copy of the slides by Tuesday night as a backup (or stick them on the slack or something).

Hope you're doing well!

**Comment by danielphil** [comment]
Hello @marksutherland! Sounds good- I'm still up for giving a talk. Either of those connections are good for my Macbook so can experiment on the day. I've got an updated version of the slides so I'll email you a link for a backup in case my laptop starts misbehaving.

Just to check- do you have a microphone for presentations? I'm a bit quiet sometimes. :\

**Comment by danielphil** [comment]
Oh- nearly forgot! Do you need a synopsis for the talk or is the title okay?

**Comment by marksutherland** [comment]
Title is all we need. There might be a mic, it seems to vary from time to time. We'll figure out what's available on the day.

**Comment by MariusCiocanel** [comment]
🚢d! Thanks Daniel
