### ISSUE TITLE
Edinburgh Techmeetup 13 July 2016

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/edinburgh#98]
## Ship List
- [ ] Email SkyScanner Reception to make sure they're ready for us
- [ ] Open Tech Calendar event ([link to event])
- [x] Drinks ordered
- [x] Drinks delivered to SkyScanner
- [x] Pizza ordered
- [x] Pizza paid for
- [x] Speakers confirmed (#75, #89  )
- [ ] Confirm volunteer to man the door
- [ ] Confirmed speakers video and internet requirements
- [x] Website updated ([link to commit])
- [x] Email announcement sent
- [ ] Confirm organisers present
    - [ ] @rwillmer
    - [x] @MariusCiocanel
    - [ ] @marshant
    - [x] @douglasm
    - [x] @marksutherland

**Comment by MariusCiocanel** [comment]
FYI @douglasm I moved the drinks from Codebase to Skyscanner last week.

**Comment by marksutherland** [comment]
Urgh, it appears I had convinced myself Daniel was going to speak in July, when that's clearly not the case. I'm going to chase up Radek and see if he can give his talk at short notice. Sorry about this :(

**Comment by marksutherland** [comment]
Radek has stepped up! WIll email and update the website later tonight.

**Comment by MariusCiocanel** [comment]
I didn't email Skyscanner reception to let them know we'll be there this evening. Have you emailed them @douglasm ? Please let me know if you haven't so i can email them.

**Comment by douglasm** [comment]
I haven't had any contact with them. Usually there is a bit of to and fro
when i order drink.

**Comment by MariusCiocanel** [comment]
I sent Skyscanner reception a short email to let them know the event is this evening.

**Comment by MariusCiocanel** [comment]
🚢 d!
