### ISSUE TITLE
Mike Ritchie  - Embedded TDD

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/edinburgh#99]
Spoke to Mike @klutz and he'd be up for giving a talk about Test Driven Development when writing software for embedded devices.

I think August would work for Mike (but we should confirm first)

@klutz we'll ask for a title and short talk description when we confirm the speaker slot for August.

Thanks for offering to talk :)

Contact @the13thcoder on Twitter

**Comment by marksutherland** [comment]
Hi @klutz, just wanted to confirm you're still up for speaking next week?

We spoke briefly last month, so I guess you know roughly how the night goes. The main things to know about speaking is that you should be aiming for 20-25mins with time for questions, there is HDMI and mini display port available if you want to present from your own laptop, and a PC with powerpoint etc. if you don't. It's best to email me a copy of the slides by Tuesday night as a backup (or upload them to the slack or somewhere else handy).

Let me know if you have any further questions or concerns and I'll see what I can do. Thanks!

**Comment by klutz** [comment]
Hi @marksutherland - yup, all good for next week. Should be fine with HDMI from my laptop (I took a sneaky look last time I was there).  I'll get the slides over to you by Tuesday.

Can you bill it as "Test-Driven Development and Design for Embedded and IoT Devices" ?

This is maybe a little cheeky, but I'd marginally prefer to be on first - reason is that there's a lot of follow-on tech detail and resources I could share with people at the break, if they're interested. Totally understand if you can't accommodate this though, perfectly happy to go with the flow.

Oh, and a question - what's the earliest time we can get access to that room for setup ?

Thanks - looking forward to it :)

**Comment by marksutherland** [comment]
Hi Mike,

As you're first to ask, you can also be first to talk :)

We usually have our first volunteers arriving from 6pm, I suspect any
earlier than that may be disruptive for Skyscanner. There should be plenty
of time to setup before most folk arrive.

Just about to send out the email and update the website, let me know if you
have any further questions. See you on Wednesday!

Mark

**Comment by klutz** [comment]
Hi @marksutherland : meant to get these to you yesterday, slides attached here as a PDF
[Link](https://github.com/techmeetup/edinburgh/files/410535/mike_ritchie_tech_meetup_edinburgh_talk.pdf)

**Comment by MariusCiocanel** [comment]
🚢d! Thanks Mike!
